;;;; Copyright (c) 1975-2017 Donald F Morrison
;;;;
;;;; Permission is hereby granted, free of charge, to any person obtaining a copy of this
;;;; software and associated documentation files (the "Software"), to deal in the Software
;;;; without restriction, including without limitation the rights to use, copy, modify,
;;;; merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
;;;; permit persons to whom the Software is furnished to do so, subject to the following
;;;; conditions:
;;;;
;;;; The above copyright notice and this permission notice shall be included in all copies
;;;; or substantial portions of the Software.
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
;;;; INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
;;;; PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
;;;; HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
;;;; CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
;;;; OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

(in-package :roan/test)

#+SBCL
(declaim (sb-ext:muffle-conditions sb-ext:compiler-note))

(defparameter *no-such-keyword* '(:no-such-keyword t))

(define-test test-method ()
  (labels ((test-m (m s n p)
             (assert-eql s (method-stage m))
             (assert-equal n (method-name m))
             (assert-equal p (method-place-notation m))))
    (let ((*default-stage* 17))
      (test-m (method) 17 nil nil)
      (test-m (method :name "foo") 17 "foo" nil)
      (test-m (method :stage 9) 9 nil nil)
      (test-m (method :stage nil) nil nil nil)
      (test-m (method :place-notation "x3") 17 nil "x3")
      (test-m (method :name "Cambridge Surprise"
                      :stage 6
                      :place-notation "x3x4x2x3x4x5,2")
              6 "Cambridge Surprise" "x3x4x2x3x4x5,2")
      (test-m (method :title "Bristol Surprise Royal") 10 "Bristol Surprise" nil)
      (test-m (method :title (format nil " Littleport  Little~CSurprise Maximus " #\Tab)
                      :stage 5)
              5 "Littleport Little Surprise" nil)
      (test-m (method :title "Littleport Little Surprise" :stage 11 :name "Glasgow")
              11 "Glasgow" nil)
      (test-m (method :title "Minor") 6 nil nil)
      (test-m (method :title nil :stage 9 :name "Grandsire") 9 "Grandsire" nil))
    (assert-error 'error
                  (method :title (format nil " ~C~C ~C   ~C " #\Tab #\Tab #\Tab #\Tab)))
    (assert-error 'type-error (method :title t :name "Plain Bob" :stage 8))
    (let ((method (method :stage 8)))
      (test-m method 8 nil nil)
      (setf (method-name method) "Pudsey Surprise")
      (test-m method 8 "Pudsey Surprise" nil)
      (setf (method-stage method) 10)
      (test-m method 10 "Pudsey Surprise" nil)
      (setf (method-stage method) 8 (method-place-notation method) "x5x6x3x4x5x6x7,2")
      (test-m method 8 "Pudsey Surprise" "x5x6x3x4x5x6x7,2")
      (setf (method-name method) nil)
      (test-m method 8 nil "x5x6x3x4x5x6x7,2")
      (setf (method-stage method) nil (method-place-notation method) nil)
      (test-m method nil nil nil)
      (setf (method-title  method) "Glazgow Little Surprise Royal")
      (test-m method 10 "Glazgow Little Surprise" nil))
    (assert-equal "Little Bob Fourteen;(ROAN:METHOD :NAME \"Little Bob\" :STAGE 14 :PLACE-NOTATION \"x1x4,2\")"
                   (let ((*package* (make-package (format nil "TEST-METHOD-TEST-PACKAGE-~A" (random 1.0))
                                                  :use '(:cl))))
                     (format nil "~A;~:*~S" (method :title "Little Bob Fourteen" :place-notation "x1x4,2"))))
    (assert-equal "Cambridge Surprise;(METHOD :NAME \"Cambridge Surprise\" :STAGE NIL)"
                   (let ((*package* (find-package :roan)))
                     (format nil "~A;~:*~S" (method :name "Cambridge Surprise" :stage nil))))
    (assert-equal "Cambridge Surprise Royal;(METHOD :NAME \"Cambridge Surprise\" :STAGE 10)"
                   (let ((*package* (find-package :roan)) (*default-stage* 10))
                     (format nil "~A;~:*~S" (method :name "Cambridge Surprise"))))
    (dolist (keys '((:title "Yorkshire Surprise Maximus")
                    (:title "Yorkshire Surprise Maximus" :stage 8)
                    (:title "Yorkshire Surprise")
                    (:name "Yorkshire Surprise" :stage 12)
                    ()
                    (:title "Little Bob Minor" :place-notation "x1x4,2")))
      (let* ((m1 (apply #'method keys))
             (m2 (eval (read-from-string (format nil "~S" m1)))))
        (assert-true (equal (method-name m1) (method-name m2)))
        (assert-true (eql (method-stage m1) (method-stage m2)))
        (assert-true (equal (method-place-notation m1) (method-place-notation m2)))
        (assert-true (equal (format nil "~A;~:*~S" m1) (format nil "~A;~:*~S" m2)))))
    ;; The malarky with with dynamic variable below is so Lisp does get smart and warn
    ;; us about the problem at compile time.
    (assert-error 'error (apply #'method *no-such-keyword*))))

(define-test test-title ()
  (labels ((test-t (name stage supply-name supply-stage title)
             (let ((args nil))
               (when supply-name
                 (push name args)
                 (push :name args))
               (when supply-stage
                 (push stage args)
                 (push :stage args))
               (let ((method (apply #'method args)))
                 (assert-equal title (method-title  method))
                 (let ((name-and-stage (multiple-value-list
                                        (parse-method-title (method-title  method)))))
                   (assert-eql 2 (length name-and-stage))
                   (assert-equal name (first name-and-stage))
                   (assert-equal stage (second name-and-stage)))))))
  (let ((*default-stage* 10))
    (test-t nil 10 nil nil "Royal")
    (test-t nil nil nil t nil)
    (test-t "Cambridge Surprise" 10 t nil "Cambridge Surprise Royal")
    (test-t "Yorkshire Surprise" nil t t "Yorkshire Surprise")))
  (let ((method (method :stage 5)))
    (setf (method-title  method) "New Cambridge Surprise Major")
    (assert-equal "New Cambridge Surprise" (method-name method))
    (assert-eql 8 (method-stage method))
    (setf (method-title  method) "Unknown Triples")
    (assert-equal "Unknown" (method-name method))
    (assert-eql 7 (method-stage method))
    (setf (method-title  method nil) "Unknown Twenty-two")
    (assert-equal "Unknown" (method-name method))
    (assert-eql 22 (method-stage method))
    (setf (method-title  method t) "Unknown Cinques")
    (assert-eq nil (method-name method))
    (assert-eql 11 (method-stage method))
    (assert-equal "Unknown Cinques" (method-title  method t))
    (assert-equal "Cinques" (method-title  method nil))
    (assert-equal "Cinques" (method-title  method))))

(define-test test-method-properties ()
  (let ((method (method :name "Advent Surprise" :stage 8
                        :place-notation "36x56.4.5x5.6x4x5x4x7,8"
                        :properties '(:first-tower "1988-07-31, Boston, Massachusetts (Advent)"))))
    (assert-equal "1988-07-31, Boston, Massachusetts (Advent)"
                  (method-property method :first-tower))
    (assert-eq nil (method-property method :ringing-world-reference))
    (assert-equal "1988/894"
                   (setf (method-property method :ringing-world-reference) "1988/894"))
    (assert-eql 4 (length (method-properties method)))
    (setf (method-properties method) nil)
    (assert-eq nil (method-properties method))
    (assert-eq :foo (method-property method :first-tower :foo))
    (push 7 (method-property method :foo '(1)))
    (incf (car (method-property method :foo)) 3)
    (assert-equal '(:foo (10 1)) (method-properties method)))
  (assert-error 'type-error (method-property nil :foo))
  (assert-error 'type-error (method-property '(1 2 3) :foo))
  (assert-error 'type-error (method-properties nil))
  (assert-error 'type-error (method-properties "Cambridgge")))

(define-test test-method-changes ()
  (let ((method (method :name "Little Bob"
                        :stage 6
                        :place-notation "x1x4,2")))
    (assert-equalp '(!214365 !132546 !214365 !132465 !214365 !132546 !214365 !124365)
                   (method-changes method))
    (let ((c1 (method-changes method)) (c2 (method-changes method)))
      (assert-true (equalp c1 c2))
      (assert-false (eq c1 c2))
      (setf (car (last c1)) :foo)
      (assert-false (equalp c1 c2)))
    (clear-method-traits method)
    (assert-equalp '(!214365 !132546 !214365 !132465 !214365 !132546 !214365 !124365)
                   (method-changes method))
    (assert-true (equalp (method-changes method)
                         (progn (clear-method-traits method) (method-changes method))))
    (setf (method-place-notation method) "4.36.25x" (method-name method) nil)
    (assert-equalp '(!132465 !213546 !124356 !214365) (method-changes method))
    (setf (method-stage method) 8)
    (assert-equalp '(!13246587 !21354687 !12435768 !21436587) (method-changes method))
    (setf (method-place-notation method) nil)
    (assert-eq nil (method-changes method))
    (setf (method-place-notation method) "x")
    (assert-equalp '(!21436587) (method-changes method))
    (setf (method-place-notation method) nil)
    (assert-eq nil (method-changes method))))

(define-test test-canonicalize-method-place-notation ()
  (let ((method (method :title "Avon Delight Maximus"
                        :place-notation "-5.-14..5Tx5.30.4x.70.1t.36-9.30.8-18.9t-18-T,1")))
    (assert-equal "x5x4.5x5.30.4x70.1.36x9.30.8x8.9x8x1,T"
                  (canonicalize-method-place-notation method))
    (assert-equal "x5x4.5x5.30.4x70.1.36x9.30.8x8.9x8x1,T"
                  (method-place-notation method))
    (canonicalize-method-place-notation method :cross #\X :upper-case nil :elide :interior)
    (assert-equal "X5X4.5X5.30.4X70.1t.36X9.30.8X8.9X8X1t,1t"
                  (method-place-notation method))))

(define-test test-contains-jump-changes ()
  (assert-false (method-contains-jump-changes
                 (method :place-notation "x3x4x2x3x4x5,2" :stage 6)))
  (assert-true (method-contains-jump-changes
                (method :place-notation "x3x(24)x2x(35)x4x5,2" :stage 6)))
  (assert-false (method-contains-jump-changes (method :stage 6)))
  (assert-false (method-contains-jump-changes
                 (method :place-notation "x3x(24)x2x(35)x4x5,2" :stage nil)))
  (assert-error 'type-error (method-contains-jump-changes nil))
  (assert-error 'type-error (method-contains-jump-changes "Cambridge Surprise Minor")))

(define-test test-lead-head ()
  (assert-equalp !15738264 (method-lead-head (method :stage 8
                                              :place-notation "x3x4x5x6x2x3x4x7,2")))
  (assert-equalp !12534 (method-lead-head (method :stage 5 :place-notation "3,1.5.1.5.1")))
  (assert-eq nil (method-lead-head (method :stage 12)))
  (assert-eq nil (method-lead-head (method :place-notation "x3x4x5x6x2x3x4x7,2" :stage nil))))

(define-test test-plain-lead ()
  (assert-equalp '(!123456 !214365 !124635 !216453 !261435 !624153 !621435 !264153 !624513
                   !265431 !256413 !524631 !256431 !524613 !542631 !456213 !546123 !451632
                   !456123 !541632 !514623 !156432 !516342 !153624)
                 (method-plain-lead (method :stage 6 :place-notation "x3x4x2x3x4x5,2")))
  (assert-eq nil (method-plain-lead (method :stage 12)))
  (assert-eq nil (method-plain-lead (method :place-notation "x3x4x5x6x2x3x4x7,2" :stage nil)))
  (let* ((m (method :place-notation "x1x4,2"))
         (p1 (method-plain-lead m))
         (p2 (method-plain-lead m)))
    (assert-true (equal p1 p2))
    (assert-false (eq p1 p2))
    (setf (car (last p1)) :foo)
    (assert-false (equal p1 p2))))

(define-test test-method-lead-length ()
  (assert-eql 24  (method-lead-length (method :title "Cambridge Surprise Minor"
                                              :place-notation "x3x4x2x3x4x5,2")))
  (assert-eql 1 (method-lead-length (method :stage 4 :place-notation "x")))
  (iter (for stage :from 5 :to +maximum-stage+)
        (if (evenp stage)
            (assert-eql 8 (method-lead-length (method :stage stage :place-notation "x1x4,2")))
            (assert-eql 6 (method-lead-length (method :stage stage
                                                      :place-notation (format nil "3.1.3,~A"
                                                                              (bell-name (1- stage))))))))
  (assert-eq nil (method-lead-length (method :title "Cambridge Surprise Minor")))
  (assert-eq nil (method-lead-length (method :stage nil :place-notation "x1x4,2")))
  (assert-error 'type-error (method-lead-length "Cambridge Surprise Minor")))

(define-test test-method-lead-count()
  (assert-eql 5 (method-lead-count (method :title "Cambridge Surprise Minor"
                                           :place-notation "x3x4x2x3x4x5,2")))
  (assert-eql 1 (method-lead-count (method :title "Cromwell Tower Block Minor"
                                           :place-notation "3x3.4x2x3x4x3,6")))
  (assert-eql 6 (method-lead-count (method :title "Bexx Differential Bob Minor"
                                           :place-notation "x1x1x23,2")))
  (assert-eql 3 (method-lead-count (method :stage 10
                                           :place-notation "x34x4x2x23x4x5x6x7x8x9,1")))
  (assert-eql 2 (method-lead-count (method :stage 12 :place-notation "x6x6x6")))
  (assert-eq nil (method-lead-count (method :title "Cambridge Surprise Minor")))
  (assert-eq nil (method-lead-count (method :stage nil :place-notation "x1x4,2")))
  (assert-error 'type-error (method-lead-count "Cambridge Surprise Minor")))


(define-test test-method-course-length ()
  (assert-eql 120 (method-course-length (method :title "Cambridge Surprise Minor"
                                           :place-notation "x3x4x2x3x4x5,2")))
  (assert-eql 24 (method-course-length (method :title "Cromwell Tower Block Minor"
                                           :place-notation "3x3.4x2x3x4x3,6")))
  (assert-eql 72 (method-course-length (method :title "Bexx Differential Bob Minor"
                                           :place-notation "x1x1x23,2")))
  (assert-eql 120 (method-course-length (method :stage 10
                                           :place-notation "x34x4x2x23x4x5x6x7x8x9,1")))
  (assert-eql 12 (method-course-length (method :stage 12 :place-notation "x6x6x6")))
  (assert-eq nil (method-course-length (method :title "Cambridge Surprise Minor")))
  (assert-eq nil (method-course-length (method :stage nil :place-notation "x1x4,2")))
  (assert-error 'type-error (method-course-length "Cambridge Surprise Minor")))

(define-test test-method-plain-course ()
  (assert-equalp '(!123456 !213465 !214356 !124365
                   !142635 !412653 !416235 !146253
                   !164523 !614532 !615423 !165432
                   !156342 !516324 !513642 !153624
                   !135264 !315246 !312564 !132546)
                 (method-plain-course (method :stage 6 :place-notation "34.2,1")))
  (assert-eq nil (method-plain-course (method :title "Cambridge Surprise Minor")))
  (assert-eq nil (method-plain-course (method :stage nil :place-notation "x1x4,2")))
  (assert-error 'type-error (method-plain-course "Cambridge Surprise Minor")))

(define-test test-method-true-plain-course-p ()
  (assert-true (method-true-plain-course-p (method :stage 8
                                                   :place-notation "x3x4x25x36x4x5x6x7,2")))
  (assert-false (method-true-plain-course-p (method :stage 8
                                                    :place-notation "x3x456x56x6x2x5.34.256x1,2")))
  (assert-error 'no-place-notation-error (method-true-plain-course-p (method :stage nil
                                                                             :place-notation "x1")))
  (assert-error 'no-place-notation-error (method-true-plain-course-p (method :stage 8)))
  (assert-error 'no-place-notation-error (method-true-plain-course-p (method :stage nil
                                                                             :place-notation "x1")
                                                                     t))
  (assert-error 'no-place-notation-error (method-true-plain-course-p (method :stage 8) t))
  (assert-false (method-true-plain-course-p (method :stage nil :place-notation "x1") nil))
  (assert-false (method-true-plain-course-p (method :stage 8) nil)))

(define-test test-hunt-working-bells ()
  (labels ((testm (stage place-notation hunt-bells working-bells)
             (let ((method (method :stage stage :place-notation place-notation)))
               (assert-equal hunt-bells (method-hunt-bells method))
               (assert-equal working-bells (method-working-bells method))
               (let ((h1 (method-hunt-bells method))
                     (h2 (method-hunt-bells method))
                     (w1 (method-working-bells method))
                     (w2 (method-working-bells method)))
                 (when h1
                   (assert-true (equal h1 h2))
                   (assert-false (eq h1 h2))
                   (setf (car (last h1)) 99)
                   (assert-false (equal h1 h2))
                   (assert-false (equal (last h1) (last h2))))
                 (when w1
                   (assert-true (equal w1 w2))
                   (assert-false (eq w1 w2))
                   (assert-true (equal (first w1) (first w2)))
                   (assert-true (equal (last w1) (last w2)))
                   (assert-false (eq (first w1) (first w2)))
                   (assert-false (eq (last w1) (last w2)))
                   (setf (car (last (last w1))) 99)
                   (assert-false (equal w1 w2))
                   (assert-false (equal (last w1) (last w2)))))
               (setf (method-stage method) nil)
               (assert-true (null (method-hunt-bells method)))
               (assert-true (null (method-working-bells method)))
               (setf (method-stage method) stage)
               (assert-equal hunt-bells (method-hunt-bells method))
               (assert-equal working-bells (method-working-bells method))
               (setf (method-place-notation method) nil)
               (assert-true (null (method-hunt-bells method)))
               (assert-true (null (method-working-bells method))))))
    (testm 5 "3,1.5.1.5.1" '(0 1) '((2 3 4)))
    (testm 12 "x1" nil '((0 2 4 6 8 10 11 9 7 5 3 1)))
    (testm 6 "-1256-1236-12-14-36-12" nil '((0 1 4) (2 5 3)))
    (testm 12 "-34-14-12.5T.30.12-70.5T.16-90.167T-ET-7T-14.36.5T,12"
           '(0 8 9) '((1 4 3 2 5) (6 10) (7 11)))
    (testm 8 "x5x4.5x5.36.4x4.5x4x1,2" '(0 1 2 3 4 5 6 7) nil)))

(defun rotate-place-notation (stage notation n)
  (let ((changes (parse-place-notation notation :stage stage)))
    (when (> n (length changes))
      (throw 'too-long nil))
    (place-notation-string (rotate changes n))))

(define-test test-method-rotations-p ()
  (labels ((test (stage notation &optional other)
             (let ((unrotated (method :stage stage :place-notation notation)))
               (assert-true (method-rotations-p unrotated unrotated))
               (when (<= (+ stage 2) +maximum-stage+)
                 (assert-false (method-rotations-p (method :stage (+ stage 2) :place-notation notation)
                                                   unrotated)))
               (catch 'too-long
                 (iter (for i :from 0)
                       (for m := (method :stage stage
                                         :place-notation (rotate-place-notation stage notation i)))
                       (for other-m := (and other
                                            (method :stage stage
                                                    :place-notation (rotate-place-notation stage other i))))
                       (assert-true (method-rotations-p m unrotated))
                       (assert-true (method-rotations-p unrotated m))
                       (when other-m
                         (assert-false (method-rotations-p unrotated other-m))
                         (assert-false (method-rotations-p m other-m))))))))
    (test 8 "34.56.3.6.5x2.36.2x4.3.6x6.7,2" "34.56.3.6.5x2.36.2x4.3.6x6.7,8")
    (test 12 "7x7x67x678,x" "7x7x67x78,x")
    (test 8 "-16-16-18-78-38-38-18-12" "-16-16-18-78-38-38-18-12.1")
    (iter (for i :from 6 :to 24 :by 2) (test i "x1x4,2" "x1x4,1"))
    (iter (for i :from 5 :to 23 :by 2)
          (test i (format nil "3.1.~A.3.1.3,1" (bell-name (- i 1))))))
  (let ((m (method :stage 8 :place-notation "x1x4,8"))
        (m2 (method :stage nil :place-notation "x1x4,8"))
        (m3 (method :stage 8)))
    (assert-error 'type-error (method-rotations-p m nil))
    (assert-error 'type-error (method-rotations-p nil m))
    (assert-error 'type-error (method-rotations-p m 17))
    (assert-error 'type-error (method-rotations-p :method m))
    (assert-error 'no-place-notation-error (method-rotations-p m m2))
    (assert-error 'no-place-notation-error (method-rotations-p m2 m2))
    (assert-error 'no-place-notation-error (method-rotations-p m2 m))
    (assert-error 'no-place-notation-error (method-rotations-p m m3))
    (assert-error 'no-place-notation-error (method-rotations-p m3 m))
    (assert-error 'no-place-notation-error (method-rotations-p m3 m3))
    (setf (method-stage m2) 6)
    (assert-error 'parse-error (method-rotations-p m m2))
    (assert-error 'parse-error (method-rotations-p m2 m))
    (assert-error 'parse-error (method-rotations-p m2 m2))))

(define-test test-classification ()
  (assert-equal '(6 7 8 9) (method-primary-hunt-bells
                            (method :stage 12 :place-notation "7x7x67x678,x")))
  (assert-equal '(4 5 6 7) (method-secondary-hunt-bells
                            (method :stage 8 :place-notation "x4x4,2")))
  (labels ((test-one (stage notation expect
                            &optional (primary nil hunts-supplied) secondary)
             (let ((method (method :stage stage :place-notation notation)))
               (assert-equal expect (method-classification method))
               (when hunts-supplied
                 (assert-equal primary (method-primary-hunt-bells method))
                 (assert-equal secondary (method-secondary-hunt-bells method)))))
           (test-rotated (stage notation expect n)
             (test-one stage (rotate-place-notation stage notation n) expect))
           (test-several (stage notation expect primary secondary)
             (test-one stage notation expect primary secondary)
             (catch 'too-long
               (iter (for i :from 1)
                     (test-rotated stage notation expect i)))))
    (macrolet ((deftest (stage notation primary secondary &rest classification)
                 `(test-several ',stage ',notation ',classification ',primary ',secondary)))
      (deftest 4 "3.1.2.1,4" (0) () :place)
      (deftest 5 "5.1.5.1.5,125" (0) () :bob)
      (deftest 5 "3.1.5.123.5,125" (0) () :bob)
      (deftest 5 "3.145.5.1.5,125" (0) () :place)
      (deftest 5 "5.1.5.3.125,125" (0) (1) :slow-course)
      (deftest 5 "5.1.5.1.125,125" (0) (4) :bob)
      (deftest 5 "3.1.5.1.5.1.5.1.5.1" (0 1) () :bob)
      (deftest 5 "3.1.5.3.1.3,1" () () :principle)
      (deftest 5 "145.3.125.3.1.3.1.3.5.1,123" () () :principle :differential)
      (deftest 5 "3.1.125.3.345,123" (0) () :bob :differential)
      (deftest 5 "5.1.5.145,125" (0) () :bob :differential :little)
      (deftest 5 "3.1.123,125" (0) (1) :slow-course :little)
      (deftest 6 "x1x1x1,2" (0) () :bob)
      (deftest 6 "x4x23.34.25,2" (0) (1) :slow-course)
      (deftest 6 "x34x4x5x23x345x5,2" (0) () :treble-place)
      (deftest 6 "x1x4,2" (0) () :bob :little)
      (deftest 6 "x1x1.5,6" (0) () :place :little)
      (deftest 6 "x3x4x2x3x4x5,2" (0) () :surprise)
      (deftest 6 "x3x4x2x1.34x2.3,2" (0) () :delight)
      (deftest 6 "x34x1x5x1x4x5,2" (0) () :treble-bob)
      (deftest 8 "34.56.3.6.5x2.3.2x34.56,2" (0) () :surprise :little)
      (deftest 6 "x3x4x2x3.4.25.34.5,2" (0) () :treble-place)
      (deftest 6 "2x2.4x2x4,6" (0) () :treble-place :little)
      (deftest 6 "x1x2x1x34x3,6" (0) () :alliance)
      (deftest 6 "x1.4.1x1x2.5,2" (0) () :alliance)
      (deftest 6 "x1.4.1x1.5,2" (0) () :alliance :little)
      (deftest 6 "x1.4.1x1.5,4" (1 2) (0) :alliance)
      (deftest 6 "34.45x3x345,2" (0) () :bob :differential)
      (deftest 6 "x34x4x25x3.4x34.5,6" (0) (5) :surprise :differential)
      (deftest 8 "x3x4x5x6x2x3.56.4.56x56.47.56.3x2x6x5x4x3x2" (0) () :hybrid)
      (deftest 8 "x5x4.5x5x4x5x36x,2" (4 5) () :hybrid :differential :little)
      (deftest 8 "x5x4.5x56.1x4x56,2" (0) () :delight :little)
      (deftest 12 "7x7x67x678,x" (6 7 8 9) () :hybrid :differential :little)
      (deftest 6 "x3x(24)x2x(35)x4x5,2" () () :jump)))
  (labels ((test-distinct (list1 list2)
             (assert-true (and (equal list1 list2)
                               (iter (for sub1 :on list1)
                                     (for sub2 :on list2)
                                     (when sub1
                                       (never (eq sub1 sub2)))))))
           (test-distinct-properties (stage notation classification primary secondary)
             (let* ((method (method :stage stage :place-notation notation))
                    (c1 (method-classification method))
                    (c2 (method-classification method))
                    (p1 (method-primary-hunt-bells method))
                    (p2 (method-primary-hunt-bells method))
                    (s1 (method-secondary-hunt-bells method))
                    (s2 (method-secondary-hunt-bells method)))
               (test-distinct classification c1)
               (test-distinct c1 c2)
               (test-distinct primary p1)
               (test-distinct p1 p2)
               (test-distinct secondary s1)
               (test-distinct s1 s2))))
    (test-distinct-properties 8 "x3x4x2x3x4.5,23"
                              '(:alliance :differential :little) '(0) nil)
    (test-distinct-properties 8 "x1x1x1x1,6"
                              '(:bob) '(0 1 2 3 4) '())
    (test-distinct-properties 8 "x4x4,2"
                              '(:bob :little) '(0) '(4 5 6 7)))
  (assert-eq nil (method-classification (method :stage 10 :name "Mumble")))
  (assert-eq nil (method-classification (method :stage nil :place-notation "x1x4,2")))
  (assert-eq nil (method-classification (method ::name "Mumble")))
  (assert-eq nil (method-classification (method)))
  (assert-error 'type-error (method-classification nil))
  (assert-error 'type-error (method-classification :method))
  (assert-error 'type-error (method-primary-hunt-bells nil))
  (assert-error 'type-error (method-primary-hunt-bells :method))
  (assert-error 'type-error (method-secondary-hunt-bells nil))
  (assert-error 'type-error (method-secondary-hunt-bells :method)))

(define-test test-set-method-classified-name ()
  (macrolet ((test (stage notation name result)
               `(let ((m (method :stage ,stage :place-notation ,notation)))
                  (set-method-classified-name m ,name)
                  (assert-equal ,result (method-name m)))))
    (test 4 "3.1.2.1,4" "Double Court" "Double Court Place")
    (test 5 "5.1.5.1.5,125" "Plain" "Plain Bob")
    (test 5 "3.1.5.123.5,125" "Huntspill" "Huntspill Bob")
    (test 5 "3.145.5.1.5,125" "Shipway" "Shipway Place")
    (test 5 "5.1.5.3.125,125" "Rugby" "Rugby Slow Course")
    (test 5 "5.1.5.1.125,125" "Boxford" "Boxford Bob")
    (test 5 "3.1.5.1.5.1.5.1.5.1" "Grandsire" "Grandsire")
    (test 5 "3.1.5.3.1.3,1" "Stedman" "Stedman")
    (test 5 "145.3.125.3.1.3.1.3.5.1,123" "Borleigh" "Borleigh Differential")
    (test 5 "3.1.125.3.345,123" "Andover" "Andover Differential Bob")
    (test 5 "5.1.5.145,125" "Baldrick" "Baldrick Differential Little Bob")
    (test 5 "3.1.123,125" "Kempton" "Kempton Little Slow Course")
    (test 6 "x1x1x1,2" "Plain" "Plain Bob")
    (test 6 "x4x23.34.25,2" "Baker Street" "Baker Street Slow Course")
    (test 6 "x34x4x5x23x345x5,2" "Apollo" "Apollo Treble Place")
    (test 6 "x1x4,2" "" "Little Bob")
    (test 6 "x1x1.5,6" "Little Little Little Little Little Little Penultimus"
          "Little Little Little Little Little Little Penultimus Little Place")
    (test 6 "x3x4x2x3x4x5,2" "Cambridge" "Cambridge Surprise")
    (test 6 "x3x4x2x1.34x2.3,2" "All Fools" "All Fools Delight")
    (test 6 "x34x1x5x1x4x5,2" "Albion" "Albion Treble Bob")
    (test 8 "34.56.3.6.5x2.3.2x34.56,2" "Shepperton" "Shepperton Little Surprise")
    (test 6 "x3x4x2x3.4.25.34.5,2" "Arthingworth" "Arthingworth Treble Place")
    (test 6 "2x2.4x2x4,6" "Unnamed" "Unnamed Little Treble Place")
    (test 6 "x1x2x1x34x3,6" "Algarkirk" "Algarkirk Alliance")
    (test 6 "x1.4.1x1x2.5,2" "Unnamed" "Unnamed Alliance")
    (test 6 "x1.4.1x1.5,2" "Unnamed" "Unnamed Little Alliance")
    (test 6 "x1.4.1x1.5,4" "Unnamed" "Unnamed Alliance")
    (test 6 "34.45x3x345,2" "Birmingham St Martin" "Birmingham St Martin Differential Bob")
    (test 6 "x34x4x25x3.4x34.5,6" "Huntly Castle" "Huntly Castle Differential Surprise")
    (test 8 "x3x4x5x6x2x3.56.4.56x56.47.56.3x2x6x5x4x3x2" "Crick" "Crick Hybrid")
    (test 8 "x5x4.5x5x4x5x36x,2" "Seven Stars" "Seven Stars Differential Little Hybrid")
    (test 8 "x5x4.5x56.1x4x56,2" "Great Orme" "Great Orme Little Delight")
    (test 12 "7x7x67x678,x" "Charm" "Charm Differential Little Hybrid")
    (test 6 "x3x(24)x2x(35)x4x5,2" "Cambridge" "Cambridge Jump"))
  (let ((m (method :stage 6 :name "Cambridge Surprise" :place-notation "x3x4x2x3x4x5,2"))
        result)
    (assert-no-error 'error (setf result (set-method-classified-name m "Cambridge")))
    (assert-equal "Cambridge Surprise" (method-name m))
    (assert-eq m result)
    (assert-no-error 'error (set-method-classified-name m "Cambridge" nil))
    (assert-equal "Cambridge Surprise" (method-name m))
    (assert-eq m result)
    (assert-no-error 'error (set-method-classified-name m "Cambridge" t))
    (assert-equal "Cambridge Surprise" (method-name m))
    (assert-eq m result)
    (assert-error 'error (setf result (set-method-classified-name m "Grantabridge")))
    (assert-equal "Cambridge Surprise" (method-name m))
    (assert-no-error 'error (set-method-classified-name m "Grantabridge" nil))
    (assert-equal "Grantabridge Surprise" (method-name m))
    (assert-eq m result)
    (assert-error 'error (setf result (set-method-classified-name m "Cambridge" t)))
    (assert-equal "Grantabridge Surprise" (method-name m)))
  (let ((m (method :stage nil)))
    (assert-eq m (set-method-classified-name m "Foo"))
    (assert-eq nil (method-name m))
    (assert-eq nil (method-stage m))
    (setf (method-stage m) 10)
    (assert-eq m (set-method-classified-name m "Foo"))
    (assert-eq nil (method-name m))
    (assert-eql 10 (method-stage m))
    (setf (method-stage m) nil)
    (setf (method-place-notation m) "x1x4,2")
    (assert-eq m (set-method-classified-name m "Foo"))
    (assert-eq nil (method-name m))
    (assert-eql nil (method-stage m))
    (assert-error 'type-error (set-method-classified-name m 17))
    (assert-error 'type-error (set-method-classified-name m 'foo))
    (setf (method-stage m) 7)
    (assert-error 'parse-error (set-method-classified-name m "Foo")))
  (assert-error 'type-error (set-method-classified-name nil "Foo"))
  (assert-error 'type-error (set-method-classified-name 'method "Foo")))

(define-test test-method-lead-head-code ()
  (labels ((test (name &optional even odd)
             (iter (for i :from +minimum-stage+ :to +maximum-stage+)
                   (when-let ((m (lookup-method name i)))
                     (if (evenp (method-stage m))
                         (assert-equal even (method-lead-head-code m))
                         (assert-equal odd (method-lead-head-code m)))))))
    (test "Plain Bob" "a" "p")
    (test "Cambridge Surprise" "b")
    (test "Cassiobury Surprise" "c")
    (test "Ashtead Surprise" "d")
    (test "Little Bob" "e")
    (test "St Simon's Bob" nil "q")
    (test "Glasgow Surprise" "g")
    (test "Essex Surprise" "h" )
    (test "Tavistock Surprise" "j")
    (test "Buckfastleigh Surprise" "k")
    (test "Cornwall Surprise" "l")
    (test "Kent Treble Bob" "m")
    (test "Stedman")
    (test "Grandsire")
    (test "Double Glasgow Surprise")
    (test "Ouse Fen Surprise" "c1")
    (test "Vernatts Surprise" "c2")
    (test "Dun Laoghaire Surprise" "d1")
    (test "Parson's Pleasure Surprise" "d2")
    (test "Doombar Surprise" "j1")
    (test "Mildmay Surprise" "j2")
    (test "Kingland Surprise" "k1")
    (test "Westland Surprise" "k2")
    (test "Hessian Surprise" "d1")
    (test "Milner Surprise" "k1")
    (test "Twerton Little Bob" nil "q1")
    (test "Little Little Little Penultimus Little Place" nil "r")
    (test "Miserden Little Bob" nil "p1")
    (test "Boston Alliance" "a")
    (test "Billy Bob Treble Place" "b")
    (test "Crick Hybrid")
    (test "London Treble Jump"))
  (assert-error 'type-error (method-lead-head-code nil))
  (assert-error 'type-error (method-lead-head-code "London Surprise Major"))
  (assert-error 'parse-error (method-lead-head-code (method :stage 5 :place-notation "x1x1x6,2"))))

(define-test test-fch-groups ()
  (assert-eql 40 (hash-table-count *fch-groups-by-name*))
  (assert-eql 840 (hash-table-count *fch-groups-by-course-head*))
  (iter (for (r g) :in-hashtable *fch-groups-by-course-head*)
        (assert-true (typep r 'row))
        (assert-true (typep g 'fch-group))
        (case (fch-group-parity g)
          ((nil) (assert-eql 8 (stage r)))
          ((:in-course) (assert-eql 10 (stage r)) (assert-true (in-course-p r)))
          ((:out-of-course) (assert-eql 10 (stage r)) (assert-false (in-course-p r)))
          (otherwise (assert-false 'bad-parity)))
        (count (and (null (fch-group-parity g)) (in-course-p r)) :into major-in-course)
        (count (and (null (fch-group-parity g)) (not (in-course-p r)))
               :into major-out-of-course)
        (count (eq (fch-group-parity g) :in-course) :into higher-in-course)
        (count (eq (fch-group-parity g) :out-of-course) :into higher-out-of-course)
        (finally (assert-eql 360 major-in-course)
                 (assert-eql 360 major-out-of-course)
                 (assert-eql 60 higher-in-course)
                 (assert-eql 60 higher-out-of-course)))
  (multiple-value-bind (capital lower-case)
      (iter (for i :from (char-code #\A) :to (char-code #\Z))
            (when-let ((g (fch-group (code-char i))))
              (collect g :into cap))
            (when-let ((g (fch-group (string-downcase (code-char i)))))
              (collect g :into lower))
            (finally (return (values cap lower))))
    (assert-eql 22 (length capital))
    (assert-eql 6 (length lower-case))
    (let ((all (hash-set)))
      (iter (for g :in capital)
            (for s := (apply #'hash-set (fch-group-elements g)))
            (assert-eql (length (fch-group-elements g)) (hash-set-count s))
            (assert-true (hash-set-empty-p (hash-set-intersection s all)))
            (setf all (hash-set-nunion s all)))
      (iter (for g :in lower-case)
            (for s := (apply #'hash-set (fch-group-elements g)))
            (assert-eql (length (fch-group-elements g)) (hash-set-count s))
            (assert-true (every #'(lambda (x) (or (not (tenors-fixed-p x)) (not (in-course-p x))))
                                (fch-group-elements g)))
            (assert-true (hash-set-empty-p (hash-set-intersection s all)))
            (setf all (hash-set-nunion s all)))
      (assert-eql 720 (hash-set-count all))
      (assert-true (every #'(lambda (x) (eql (bell-at-position x 0) 0)) (hash-set-elements all)))
      (assert-true (every #'(lambda (x) (tenors-fixed-p x 7)) (hash-set-elements all))))
    (iter (for g :in (append capital lower-case))
          (assert-true (every #'(lambda (x) (eq (fch-group x) g))
                              (fch-group-elements g)))
          (assert-true (notany #'(lambda (x) (eq (fch-group (alter-stage x 10)) g))
                              (fch-group-elements g)))))
  (multiple-value-bind (in-course out-of-course)
      (iter (for i :from (char-code #\A) :to (char-code #\Z))
            (when-let ((g (fch-group (code-char i) t nil)))
              (collect g :into in-course))
            (when-let ((g (fch-group (format nil "~C1" (code-char i)) t nil)))
              (collect g :into in-course))
            (when-let ((g (fch-group (format nil "~C2" (code-char i)) t nil)))
              (collect g :into in-course))
            (when-let ((g (fch-group (string-downcase (code-char i)) t nil)))
              (collect g :into in-course))
            (when-let ((g (fch-group (format nil "~(~C~)1" (code-char i)) t nil)))
              (collect g :into in-course))
            (when-let ((g (fch-group (format nil "~(~C~)2" (code-char i)) t nil)))
              (collect g :into in-course))
            (when-let ((g (fch-group (code-char i) t t)))
              (collect g :into out-of-course))
            (when-let ((g (fch-group (format nil "~C1" (code-char i)) t t)))
              (collect g :into out-of-course))
            (when-let ((g (fch-group (format nil "~C2" (code-char i)) t t)))
              (collect g :into out-of-course))
            (when-let ((g (fch-group (string-downcase (code-char i)) t t)))
              (collect g :into out-of-course))
            (when-let ((g (fch-group (format nil "~(~C~)1" (code-char i)) t t)))
              (collect g :into out-of-course))
            (when-let ((g (fch-group (format nil "~(~C~)2" (code-char i)) t t)))
              (collect g :into out-of-course))
            (finally (return (values in-course out-of-course))))
    (assert-eql 22 (length in-course))
    (assert-eql 19 (length out-of-course))
    (let ((all (hash-set)))
      (iter (for g :in in-course)
            (for s := (apply #'hash-set (fch-group-elements g)))
            (assert-eql (length (fch-group-elements g)) (hash-set-count s))
            (assert-true (every #'in-course-p (fch-group-elements g)))
            (assert-true (hash-set-empty-p (hash-set-intersection s all)))
            (setf all (hash-set-nunion s all)))
      (iter (for g :in out-of-course)
            (for s := (apply #'hash-set (fch-group-elements g)))
            (assert-eql (length (fch-group-elements g)) (hash-set-count s))
            (assert-true (every #'(lambda (x) (not (in-course-p x))) (fch-group-elements g)))
            (assert-true (hash-set-empty-p (hash-set-intersection s all)))
            (setf all (hash-set-nunion s all)))
      (assert-eql 120 (hash-set-count all))
      (assert-true (every #'(lambda (x) (eql (bell-at-position x 0) 0)) (hash-set-elements all)))
      (assert-true (every #'(lambda (x) (tenors-fixed-p x)) (hash-set-elements all))))
    (iter (for g :in (append in-course out-of-course))
          (assert-true (every #'(lambda (x) (eq (fch-group x) g))
                              (fch-group-elements g)))
          (assert-true (every #'(lambda (x) (eq (fch-group (alter-stage x 12)) g))
                              (fch-group-elements g)))
          (assert-true (every #'(lambda (x) (eq (fch-group (alter-stage x 24)) g))
                              (fch-group-elements g)))
          (assert-true (notany #'(lambda (x) (eq (fch-group (alter-stage x 8)) g))
                               (fch-group-elements g)))))
  (assert-true (member !2436578 (fch-group-elements (fch-group "B")) :test #'equalp))
  (assert-true (member !2436578 (fch-group-elements (fch-group "B" nil)) :test #'equalp))
  (assert-true (member !2436578 (fch-group-elements (fch-group "B" nil nil)) :test #'equalp))
  (assert-false (member !3246578 (fch-group-elements (fch-group "B")) :test #'equalp))
  (assert-true (member !243657890 (fch-group-elements (fch-group "B" t)) :test #'equalp))
  (assert-true (member !243657890 (fch-group-elements (fch-group "B" t nil)) :test #'equalp))
  (assert-false (member !243657890 (fch-group-elements (fch-group "B" t t)) :test #'equalp))
  (assert-false (member !324657890 (fch-group-elements (fch-group "B" t)) :test #'equalp))
  (assert-false (member !324657890 (fch-group-elements (fch-group "B" t nil)) :test #'equalp))
  (assert-false (member !324657890 (fch-group-elements (fch-group "B" t t)) :test #'equalp))
  (assert-false (member !324567890 (fch-group-elements (fch-group "B" t)) :test #'equalp))
  (assert-false (member !324567890 (fch-group-elements (fch-group "B" t nil)) :test #'equalp))
  (assert-true (member !324567890 (fch-group-elements (fch-group "B" t t)) :test #'equalp))
  (assert-true (member !3245678 (fch-group-elements (fch-group "B")) :test #'equalp))
  (assert-true (member !3245678 (fch-group-elements (fch-group "B" nil)) :test #'equalp))
  (assert-true (member !3245678 (fch-group-elements (fch-group "B" nil nil)) :test #'equalp))
  (assert-false (member !324567890 (fch-group-elements (fch-group "B" t)) :test #'equalp))
  (assert-false (member !324567890 (fch-group-elements (fch-group "B" t nil)) :test #'equalp))
  (assert-true (member !324567890 (fch-group-elements (fch-group "B" t t)) :test #'equalp))
  (assert-true (member (rounds 8) (fch-group-elements (fch-group "A")) :test #'equalp))
  (assert-true (member !13254768 (fch-group-elements (fch-group "A")) :test #'equalp))
  (assert-true (member (rounds 10) (fch-group-elements (fch-group "A" t)) :test #'equalp))
  (assert-eq nil (fch-group "A" t t))
  (assert-equal "B" (fch-group-name (fch-group !2436578)))
  (assert-eq nil (fch-group-parity (fch-group !2436578)))
  (assert-equal "E" (fch-group-name (fch-group !3246578)))
  (assert-equal "f" (fch-group-name (fch-group !5462378)))
  (assert-equal "K" (fch-group-name (fch-group !5234678)))
  (assert-equal "K1" (fch-group-name (fch-group !523467890)))
  (assert-eq :out-of-course (fch-group-parity (fch-group !523467890)))
  (assert-equal "U" (fch-group-name (fch-group !3526478)))
  (assert-equal "U2" (fch-group-name (fch-group !352647890)))
  (assert-eq :in-course (fch-group-parity (fch-group !352647890)))
  (assert-equal "a" (fch-group-name (fch-group !2354678)))
  (assert-equal "a2" (fch-group-name (fch-group !235467890ET)))
  (assert-eq nil (fch-group-parity (fch-group !2436578)))
  (assert-eq nil (fch-group-parity (fch-group !3246578)))
  (assert-eq nil (fch-group !1325476890))
  (assert-eq nil (fch-group !21435678))
  (assert-eq nil (fch-group !2143567890))
  (assert-eq nil (fch-group !12435687))
  (assert-eq nil (fch-group "W"))
  (assert-eq nil (fch-group "W" t))
  (assert-eq nil (fch-group "W" t t))
  (assert-eq nil (fch-group "w"))
  (assert-eq nil (fch-group "w" t))
  (assert-eq nil (fch-group "w" t t))
  (assert-eq nil (fch-group !1243657))
  (assert-error 'type-error (fch-group 12436578))
  (locally
      #+SBCL (declare (sb-ext:muffle-conditions warning))
    ;; SBCL is too clever and moans about these at compile time, hence the declaration
    (assert-error 'type-error (fch-group-name nil))
    (assert-error 'type-error (fch-group-parity nil))
    (assert-error 'type-error (fch-group-elements nil))
    (assert-error 'type-error (fch-group-name :foo))
    (assert-error 'type-error (fch-group-parity :foo))
    (assert-error 'type-error (fch-group-elements :foo))
    (assert-error 'type-error (fch-group-name 7))
    (assert-error 'type-error (fch-group-parity 8))
    (assert-error 'type-error (fch-group-elements 9))
    (assert-error 'type-error (fch-group-name !12436578))
    (assert-error 'type-error (fch-group-parity !1243657890))
    (assert-error 'type-error (fch-group-elements !1243657890ET)))
  (assert-error 'error (fch-group !12436578 t))
  (assert-error 'error (fch-group !12436578 t nil))
  (assert-error 'error (fch-group !12436578 t t))
  (assert-error 'error (fch-group !12436578 nil))
  (with-sink-stream
    (assert-prints "B" (princ (fch-group !12436578)))
    (assert-prints "B" (princ (fch-group !1243657890)))
    (assert-prints "a1" (princ (fch-group !1234657890)))
    (assert-prints "L2" (princ (fch-group "L2" t)))
    (assert-prints "a2" (princ (fch-group "a2" t t)))
    (let ((*print-readably* t))
      (assert-prints "(FCH-GROUP \"B\")" (prin1 (fch-group !12436578)))
      (assert-prints "(FCH-GROUP \"B\" T NIL)" (prin1 (fch-group !1243657890)))
      (assert-prints "(FCH-GROUP \"a1\" T T)" (prin1 (fch-group !1234657890)))
      (assert-prints "(FCH-GROUP \"L2\" T NIL)" (prin1 (fch-group "L2" t)))
      (assert-prints "(FCH-GROUP \"a2\" T T)" (prin1 (fch-group "a2" t t)))))
  (labels ((group-list (name &rest args)
             (when-let ((g (apply #'fch-group name args)))
               (list g)))
           (test-strings (major higher-1 higher-2 higher-3 &rest strings)
             (iter (for list :in strings)
                   (for i :from 0)
                   (collect (mapcan #'group-list list) :into g8)
                   (collect (mapcan #'(lambda (x) (group-list x t (oddp i))) list) :into g10+)
                   (collect (mapcan #'(lambda (x) (group-list x t (evenp i))) list) :into g10-)
                   (finally
                    (assert-equal major (apply #'fch-groups-string g8))
                    (assert-equal higher-1 (apply #'fch-groups-string g10+))
                    (assert-equal higher-2 (apply #'fch-groups-string g10-))
                    (assert-equal higher-3 (apply #'fch-groups-string (append g10- g10+)))
                    (when (and (flatten g8) (flatten g10+))
                      (assert-error 'mixed-stage-fch-groups-error
                                    (apply #'fch-groups-string (append g8 g10+))))
                    (when (and (flatten g8) (flatten g10-))
                      (assert-error 'mixed-stage-fch-groups-error
                                    (apply #'fch-groups-string (append g10- g8))))))))
    (test-strings "BDc" "BD/" "/BDc" "BD/BDc"
                  '("B" "D" "c"))
    (test-strings "BDc" "BD/BDc" "BD/BDc" "BD/BDc"
                  '("B" "D" "c") '("D" "B" "c") '("D" "c" "B") '("B" "c" "D") '("B" "D" "c"))
    (test-strings nil nil nil nil '())
    (test-strings "ABCDEFGHIKMNX" "ABCDEFGHIKL1MN/" "/BCDEFHa2" "ABCDEFGHIKL1MN/BCDEFHa2"
                  '("a2" "N" "M" "X" "L1" "K" "I" "H" "G" "F" "E" "D" "C" "B") '() '("X" "A" "G")))
  (assert-equal "AKUdX" (fch-groups-string (vector (fch-group "d") (fch-group "K"))
                                           (list (fch-group "X") (fch-group "A"))
                                           (hash-set (fch-group "K") (fch-group "U")))))

(define-test test-method-falseness ()
  (labels ((test-fch-summary (name stage result)
             (multiple-value-bind (ignore-1 groups ignore-2)
                 (method-falseness (lookup-method name stage))
               (declare (ignore ignore-1 ignore-2))
               (assert-equal result (fch-groups-string groups)))))
    (test-fch-summary "Cambridge Surprise" 8 "BDEe")
    (test-fch-summary "Bristol Surprise" 8 "c")
    (test-fch-summary "Budapest Surprise" 8 "BcdY")
    (test-fch-summary "Colston Arms Surprise" 8 "DKLOTa")
    (test-fch-summary "Double Darrowby Surprise" 8 "BCDEFKLMPTUabcd")
    (test-fch-summary "Othorpe Surprise" 8 "BDXY")
    (test-fch-summary "Heywood Alliance" 8 "a")
    (test-fch-summary "Double Glasgow Surprise" 8 nil)
    (test-fch-summary "Little Bob" 8 nil)
    (test-fch-summary "Cumberland Bob" 8 nil)
    (test-fch-summary "Normandy Surprise" 8 "ABa")
    (test-fch-summary "Crick Hybrid" 8 nil)
    (test-fch-summary "Cambridge Surprise" 10 "BD/B")
    (test-fch-summary "Old Surprise" 10 "/BK1a1c")
    (test-fch-summary "Zorin Surprise" 10 "T/BDa1c")
    (test-fch-summary "Cambridge Surprise" 12 "D/B")
    (test-fch-summary "Swindon Surprise" 12 "/Bc")
    (test-fch-summary "Cambridge Surprise" 14 "D/B")
    (test-fch-summary "Tauron Surprise" 14 "/Oc")
    (test-fch-summary "Cambridge Surprise" 16 "D/B")
    (test-fch-summary "Phobos Moon Surprise" 16 "D/BDa2"))
  (assert-equalp (hash-set !3254678 !3246578 !2436578 !4326578 !4625378 !3245678
                           !4253678 !3524678 !2543678 !5342678 !2463578 !2365478
                           !2435768 !2354768 !3524768 !5234768 !5342768 !4236758
                           !2345768 !3254768 !4263758 !6452738 !3427568 !2647358
                           !3547628 !2567438 !6327458 !3274568 !3572468 !5374268
                           !5276348 !4372658 !6274538 !2734568 !6745238 !2745638
                           !2435678 !4325678 !4265378 !3625478 !6345278 !2456738
                           !5263748 !6352748 !2357468 !5237468 !2347658 !3275648
                           !2573648 !5372648 !7254368 !7543628 !7236548 !7365428
                           !7243658 !7654328)
                 (apply #'hash-set (method-falseness (lookup-method "Belfast Surprise" 8))))
  (assert-equalp (hash-set !1325467890ET !1462537890ET !1324567890ET
                           !1432567890ET !1254367890ET !1236547890ET)
                 (apply #'hash-set (method-falseness (lookup-method "Cambridge Surprise" 12))))
  (iter (with incidence := (third (multiple-value-list
                                   (method-falseness
                                    (lookup-method "Cambridge Surprise" 10)))))
        (for i :from 0 :below 9)
        (iter (for j :from 0 :below 9)
              (when-let ((x (aref incidence i j)))
                (setf (aref incidence i j) (apply #'hash-set x))))
        (finally
         (assert-equalp (make-array '(9 9) :initial-contents
                                    `((nil nil nil nil nil nil nil nil nil)
                                      (nil nil nil nil nil nil nil nil nil)
                                      (nil nil nil nil nil nil nil nil nil)
                                      (nil ,(hash-set !1243657890) nil nil nil nil nil nil nil)
                                      (,(hash-set !1432567890 !1254367890) nil nil nil nil nil nil nil nil)
                                      (,(hash-set !1462537890 !1324567890) ,(hash-set !1325467890 !1254367890) nil nil nil
                                        nil nil nil nil)
                                      (nil nil nil nil nil nil nil nil nil)
                                      (nil nil nil ,(hash-set !1462537890 !1236547890) nil ,(hash-set !1243657890) nil nil
                                           nil)
                                      (nil nil nil ,(hash-set !1325467890 !1432567890) ,(hash-set !1324567890 !1236547890)
                                           nil nil nil nil)))
                        incidence)))
  (assert-error 'type-error (method-falseness nil))
  (assert-error 'type-error (method-falseness "Cambridge Surprise Major"))
  (assert-error 'parse-error (method-falseness (method :stage 8 :place-notation "9.2,0")))
  (assert-error 'no-place-notation-error (method-falseness (method)))
  (assert-error 'no-place-notation-error (method-falseness (method :stage 12)))
  (assert-error 'no-place-notation-error (method-falseness (method :stage nil :place-notation "x1x4,2")))
  (assert-error 'inappropriate-method-error (method-falseness (lookup-method "Stedman" 7)))
  (assert-error 'inappropriate-method-error (method-falseness (lookup-method "Stedman" 11)))
  (assert-error 'inappropriate-method-error (method-falseness (lookup-method "Grandsire" 9)))
  (assert-error 'inappropriate-method-error (method-falseness (lookup-method "Grandsire" 8)))
  (assert-error 'inappropriate-method-error (method-falseness (lookup-method "Grandsire" 10)))
  (assert-error 'inappropriate-method-error (method-falseness (lookup-method "Temple Meads Differential Surprise" 10))))

(define-test test-lookup-methods-by-name ()
  (let ((m (lookup-methods-by-name "Advent Surprise" :stage 8)))
    (assert-eql 1 (length m))
    (setf m (first m))
    (assert-equal "Advent Surprise Major" (method-title m))
    (assert-eql 8 (method-stage m))
    (assert-equal "36x56.4.5x5.6x4x5x4x7,8" (method-place-notation m))
    (assert-equal "1988-07-31 at Boston, Massachusetts, USA (Advent)"
                  (method-property m :first-tower)))
  (let ((m (lookup-method "Advent Surprise" 8)))
    (assert-equal "Advent Surprise Major" (method-title m))
    (assert-eql 8 (method-stage m))
    (assert-equal "36x56.4.5x5.6x4x5x4x7,8" (method-place-notation m))
    (assert-equal "1988-07-31 at Boston, Massachusetts, USA (Advent)"
                  (method-property m :first-tower)))
  (let* ((*default-stage* 8) (m (lookup-methods-by-name "advenT surPrise")))
    (assert-eql 1 (length m))
    (setf m (first m))
    (assert-equal "Advent Surprise Major" (method-title m))
    (assert-eql 8 (method-stage m))
    (assert-equal "36x56.4.5x5.6x4x5x4x7,8" (method-place-notation m))
    (assert-equal "1988-07-31 at Boston, Massachusetts, USA (Advent)"
                  (method-property m :first-tower)))
  (let* ((*default-stage* 8) (m (lookup-method "advenT surPrise")))
    (assert-equal "Advent Surprise Major" (method-title m))
    (assert-eql 8 (method-stage m))
    (assert-equal "36x56.4.5x5.6x4x5x4x7,8" (method-place-notation m))
    (assert-equal "1988-07-31 at Boston, Massachusetts, USA (Advent)"
                  (method-property m :first-tower)))
  (let ((m (lookup-methods-by-name "A?vent Surpr*" :stage 8)))
    (assert-eql 1 (length m))
    (setf m (first m))
    (assert-equal "Advent Surprise Major" (method-title m))
    (assert-eql 8 (method-stage m))
    (assert-equal "36x56.4.5x5.6x4x5x4x7,8" (method-place-notation m))
    (assert-equal "1988-07-31 at Boston, Massachusetts, USA (Advent)"
                  (method-property m :first-tower)))
  (let ((m (lookup-method "A?vent Surpr*" 8)))
    (assert-equal "Advent Surprise Major" (method-title m))
    (assert-eql 8 (method-stage m))
    (assert-equal "36x56.4.5x5.6x4x5x4x7,8" (method-place-notation m))
    (assert-equal "1988-07-31 at Boston, Massachusetts, USA (Advent)"
                  (method-property m :first-tower)))
  (let ((m (find "Cambridge Surprise" (lookup-methods-by-name "Cambridge *" :stage 8)
                 :key #'method-name :test #'equal)))
    (assert-equal "x3x4x25x36x4x5x6x7,2" (method-place-notation m)))
  (let ((m (find "Cambridge Surprise" (lookup-methods-by-name "C*e S*" :stage 8)
                 :key #'method-name :test #'equal)))
    (assert-equal "x3x4x25x36x4x5x6x7,2" (method-place-notation m)))
  (let ((m (find "Cambridge Surprise" (lookup-methods-by-name "c?*?*?E *******S?*?" :stage 8)
                 :key #'method-name :test #'equal)))
    (assert-equal "x3x4x25x36x4x5x6x7,2" (method-place-notation m)))
  (iter (for *default-stage* :from +minimum-stage+ :to +maximum-stage+)
        (assert-eq nil (lookup-methods-by-name "no-such-method-please"))
        (assert-eq nil (lookup-methods-by-name "*no-such-method-please*"))
        (assert-eq nil (lookup-methods-by-name "\\*"))
        (assert-eq nil (lookup-methods-by-name "\\?"))
        (assert-eq nil (lookup-methods-by-name "\\\\"))
        (assert-eq nil (lookup-methods-by-name ""))
        (assert-eq nil (lookup-method "no-such-method-please"))
        (assert-eq nil (lookup-method "*no-such-method-please*"))
        (assert-eq nil (lookup-method "\\*"))
        (assert-eq nil (lookup-method "\\?"))
        (assert-eq nil (lookup-method "\\\\"))
        (assert-eq nil (lookup-method "")))
  (iter (for i :from 5 :to 15 :by 2)
        (for m := (lookup-methods-by-name "Stedman" :stage i))
        (assert-eql 1 (length m))
        (assert-equal (format nil "3.1.~A.3.1.3,1" (bell-name (- i 1) t))
                      (and m (method-place-notation (first m))))
        (assert-equal (format nil "3.1.~A.3.1.3,1" (bell-name (- i 1) t))
                      (method-place-notation (lookup-method "Stedman" i))))
  (iter (for i :from 6 :to 22 :by 2)
        (for m := (lookup-methods-by-name "Little Bob" :stage i))
        (assert-eql 1 (length m))
        (assert-equal "x1x4,2" (and m (method-place-notation (first m))))
        (assert-equal "x1x4,2" (method-place-notation (lookup-method "Little Bob" i))))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage nil))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage "8"))
  (assert-error 'type-error (lookup-methods-by-name nil :stage 8))
  (assert-error 'type-error (lookup-methods-by-name '|Advent Surprise|) :stage 8)
  (assert-error 'type-error (lookup-method "Advent Surprise"nil))
  (assert-error 'type-error (lookup-method "Advent Surprise" "8"))
  (assert-error 'type-error (lookup-method nil 8))
  (assert-error 'type-error (lookup-method '|Advent Surprise|) 8)
  (locally
      #+SBCL (declare (sb-ext:muffle-conditions warning))
    (let ((*fn* (and (lookup-method "Advent Surprise" 8) #'lookup-method)))
      ;; dynamic binding is to stop the compiler from being so smart it detects the error at compile time
      ;; SBCL is too smart even for that, hence the previous declaration
      (declare (special *fn*))
      (assert-error 'error (apply *fn* "Advent Surprise" 8 :limit 2))
      (assert-error 'error (apply *fn* "Advent Surprise" 8 :update t))
      (assert-error 'error (apply *fn* "Advent Surprise" 8 :busy-timeout 2))))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :limit 0))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :limit :one))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :database 17))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :busy-timeout "10"))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :busy-timeout '|10|))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :busy-timeout -1))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :update :yup))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :update -1))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :url 100))
  (assert-error 'type-error (lookup-methods-by-name "Advent Surprise" :stage 8 :update 0 :url 0))
  (assert-error 'error (lookup-methods-by-name "Advent Surprise" :stage 8 :database "no-such-db")))

(define-test test-lookup-methods-by-notation-and-changes ()
  (labels ((same-method-p (m1 m2)
             (and (eql (method-stage m1) (method-stage m2))
                  (equal (method-name m1) (method-name m2))
                  (equal (method-place-notation m1) (method-place-notation m2))
                  (equal (method-property m1 :first-tower) (method-property m2 :first-tower))
                  (equal (method-property m1 :first-hand) (method-property m2 :first-hand)))))
    (macrolet ((test ((var stage notation &rest args) &body body)
                 `(let ((changes (parse-place-notation ',notation :stage ,stage))
                        (by-notation (apply #'lookup-methods-by-notation ',notation
                                            :stage ,stage
                                            ',args)))
                    (let ((,var by-notation))
                      (iter (for m :in ,var)
                            (assert-eql ,stage (method-stage m)))
                      ,@body)
                    (let ((,var (apply #'lookup-methods-from-changes changes ',args)))
                      (assert-eql (length by-notation) (length ,var))
                      (iter (for result :in by-notation)
                            (assert-true (member result ,var :test #'same-method-p)))
                      (iter (for m :in ,var)
                            (assert-eql ,stage (method-stage m)))
                      ,@body)))
               (test-error (err stage notation &rest args)
                 `(let ((changes (parse-place-notation ',notation :stage ,stage)))
                    (assert-error ',err (apply #'lookup-methods-by-notation
                                               ',notation
                                               :stage ,stage
                                               ',args))
                    (assert-error ',err (apply #'lookup-methods-from-changes
                                               changes
                                               ',args)))))
      (test (x 5 "3,1.5.1.5.1")
        (assert-eql 1 (length x))
        (assert-equal "Grandsire" (method-name (first x))))
      (test (x 5 "3,1.5.1.5.1" :rotations nil)
        (assert-eql 1 (length x))
        (assert-equal "Grandsire" (method-name (first x))))
      (test (x 5 "3,1.5.1.5.1" :rotations t)
        (assert-eql 2 (length x))
        (assert-true (member "Grandsire" x :key #'method-name :test #'equal))
        (assert-true (member "New Grandsire" x :key #'method-name :test #'equal)))
      (test (x 5 "5.1.5.1,1.3" :rotations :yes)
        (assert-eql 2 (length x))
        (assert-true (member "Grandsire" x :key #'method-name :test #'equal))
        (assert-true (member "New Grandsire" x :key #'method-name :test #'equal)))
      (test (x 5 "5,1.3.1")
        (assert-eql 3 (length x))
        (assert-true (member "Bastow Little Bob" x :key #'method-name :test #'equal))
        (assert-true (member "St Helen's" x :key #'method-name :test #'equal))
        (assert-true (member "Cloister" x :key #'method-name :test #'equal)))
      (test (x 5 "5,1.3.1" :rotations t)
        (assert-eql 3 (length x))
        (assert-true (member "Bastow Little Bob" x :key #'method-name :test #'equal))
        (assert-true (member "St Helen's" x :key #'method-name :test #'equal))
        (assert-true (member "Cloister" x :key #'method-name :test #'equal)))
      (test (x 5 "5,1.3.1" :limit 9999999)
        (assert-eql 3 (length x))
        (assert-true (member "Bastow Little Bob" x :key #'method-name :test #'equal))
        (assert-true (member "St Helen's" x :key #'method-name :test #'equal))
        (assert-true (member "Cloister" x :key #'method-name :test #'equal)))
      (test (x 5 "5,1.3.1" :limit 2)
        (assert-eql 2 (length x))
        (assert-true (every #'(lambda (m)
                                (member (method-name m)
                                        '("Bastow Little Bob" "St Helen's" "Cloister")
                                        :test #'equal))
                            x)))
      (test (x 5 "5,1.3.1" :limit 2 :rotations t)
        (assert-eql 2 (length x))
        (assert-true (every #'(lambda (m)
                                (member (method-name m)
                                        '("Bastow Little Bob" "St Helen's" "Cloister")
                                        :test #'equal))
                            x)))
      (test (x 5 "5,1.3.1" :limit 1)
        (assert-eql 1 (length x))
        (member (method-name (first x)) '("Bastow Little Bob" "St Helen's" "Cloister")
                :test #'equal))
      (iter (for i :from +minimum-stage+ :to +maximum-stage+)
            (test (x i "1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1")
              (assert-eq nil x)))
      (iter (for i :from +minimum-stage+ :to +maximum-stage+)
            (test (x i "1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1" :rotations t)
              (assert-eq nil x)))
      (iter (for i :from +minimum-stage+ :to +maximum-stage+)
            (test (x i "1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1" :limit 1)
              (assert-eq nil x)))
      (iter (for i :from 6 :to 22 :by 2)
            (test (x i "x1x4,2")
              (assert-eql 1 (length x))
              (assert-equal "Little Bob" (method-name (first x)))))
      (test-error type-error 10 "x1x4,2" :limit 0)
      (test-error type-error 10 "x1x4,2" :limit -99)
      (test-error type-error 10 "x1x4,2" :limit t)
      (test-error type-error 10 "x1x4,2" :database 33)
      (test-error type-error 10 "x1x4,2" :busy-timeout -1)
      (test-error type-error 10 "x1x4,2" :busy-timeout "60")
      (test-error type-error 10 "x1x4,2" :busy-timeout '|60|)
      (test-error type-error 10 "x1x4,2" :update :nope)
      (test-error type-error 10 "x1x4,2" :update '(20))
      (test-error type-error 10 "x1x4,2" :url 19)
      (test-error type-error 10 "x1x4,2" :update t :url :site))))

(define-test test-with-methods-database ()
  (assert-equal '(6 8 10 12 14 16)
                (sort (with-methods-database (conn)
                        (iter (for (stage) :in-sqlite-query
                                   "select stage from methods where name = 'Cambridge Surprise'"
                                   :on-database conn)
                              (collect stage)))
                      #'<))
  (assert-eq nil (with-methods-database (conn) (declare (ignore conn))))
  (assert-equal '(1 2 3)
                (multiple-value-list (with-methods-database (conn)
                                       (declare (ignore conn))
                                       (values 1 2 3))))
  (assert-error 'type-error (with-methods-database (conn :database 17) (declare (ignore conn)) nil))
  (assert-error 'type-error (with-methods-database (conn :busy-timeout -1) (declare (ignore conn)) nil))
  (assert-error 'type-error (with-methods-database (conn :busy-timeout t) (declare (ignore conn)) nil)))

(defmacro with-temp-filename ((name-var &optional preserve) &body body)
  `(%with-temp-filename #'(lambda (,name-var) ,@body) ,preserve))

(defun %with-temp-filename (thunk preserve)
  (let (temp temp-name)
    (unwind-protect
         (progn
           (setf temp (cl-fad:open-temporary))
           (setf temp-name (pathname temp))
           (close temp)
           (unless preserve
             (delete-file temp-name))
           (setf temp nil)
           (funcall thunk temp-name))
      (when temp
        (close temp))
      (when (probe-file temp-name)
        (delete-file temp-name)))))

(defparameter *artificial-database-contents*
  '((foo6 6 "Foo" "x3x3x3x3x3x3x3x3x3x3x3x3,4" "fribble" "frob")
    (foo8 8 "Foo" "x3x3x3x3x3x3x3x3x3x3x3x3,4" nil nil)
    (star 7 "*" "1" nil "star")
    (foo10 10 "Foo" "x3x3x3x3x3x3x3x3x3x3x3x3,4" "floop" nil)
    (star2 7 "x * x" "1" nil nil)
    (foo10* 10 "Foo*" "x3x3x3x3x3x3x3x3x3x3x3x3,4" nil "ickyicky")
    (question 7"?" "1" nil nil)
    (backslash 7 "\\\\" "1" "stuff" nil)
    (foo12 12 "Foo" "x3x3x3x3x3x3x3x3x3x3x3x3,4" nil "frobozo")
    (backslash2 7 "\\\\\\\\xxx\\\\\\\\" "1" nil "thingie")
    (backslash3 9 "\\\\\\\\xxx\\\\\\\\" "1" nil nil)
    (question2 7 "x  ???  x   ???   x" "1" nil nil)))

(define-test test-using-artificial-database ()
  (with-temp-filename (path t)
    (with-methods-database (connection :database path)
      (sqlite:with-transaction connection
        (sqlite:execute-non-query connection "create table methods (stage int, name text,
                                              notation text, canonicalRotation text,
                                              firstTower text, firstHand text)")
        (sqlite:execute-non-query connection "create table version (updated text non null, etag text)")
        (iter (for (nil stage name notation tower hand) :in *artificial-database-contents*)
              (sqlite:execute-non-query connection
                                        "insert into methods values (?, ?, ?, ?, ?, ?)"
                                        stage
                                        name
                                        notation
                                        (with-initial-format-characters
                                          (place-notation-string (canonical-rotation
                                                                  (parse-place-notation notation :stage stage))
                                                                 :comma t))
                                        tower
                                        hand))
        (sqlite:execute-non-query connection "insert into version values (current_timestamp, null)")))
    (prepare-database path "the-etag")
    (macrolet ((test-method (key method)
                 (once-only (method)
                   `(destructuring-bind (stage name notation tower hand)
                        (cdr (assoc ,key *artificial-database-contents*))
                      (assert-typep 'method ,method)
                      (when (typep ,method 'method)
                        (assert-eql stage (method-stage ,method))
                        (assert-equal name (method-name ,method))
                        (assert-equal notation (method-place-notation ,method))
                        (assert-equal tower (method-property ,method :first-tower))
                        (assert-equal hand (method-property ,method :first hand)))))))
      (let ((m (lookup-methods-by-name "Foo" :stage 6 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo6 (first m)))
      (let ((m (lookup-methods-by-notation "x3x3x3x3x3x3x3x3x3x3x3x3,4" :stage 6 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo6 (first m)))
      (let ((m (lookup-methods-by-name "Foo" :stage 8 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo8 (first m)))
      (let ((m (lookup-methods-by-notation "x3x3x3x3x3x3x3x3x3x3x3x3,4" :stage 8 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo8 (first m)))
      (let ((m (lookup-methods-by-name "Foo" :stage 10 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo10 (first m)))
      (let ((m (lookup-methods-by-notation "x3x3x3x3x3x3x3x3x3x3x3x3,4" :stage 10 :database path)))
        (assert-eql 2 (length m))
        (test-method 'foo10 (find "Foo" m :key #'method-name :test #'equal))
        (test-method 'foo10* (find "Foo*" m :key #'method-name :test #'equal)))
      (let ((m (lookup-methods-by-notation "x3x3x3x3x3x3x3x3x3x3x3x3,4" :stage 10 :database path :limit 1)))
        (assert-eql 1 (length m))
        (test-method (if (find "Foo" m :key #'method-name :test #'equal) 'foo10 'foo10*) (first m)))
      (let ((m (lookup-methods-by-name "Foo" :stage 12 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo12 (first m)))
      (let ((m (lookup-methods-by-notation "x3x3x3x3x3x3x3x3x3x3x3x3,4" :stage 12 :database path)))
        (assert-eql 1 (length m))
        (test-method 'foo12 (first m)))
      (iter (for i :from +minimum-stage+ :to +maximum-stage+)
            (unless (member i '(6 8 10 12))
              (assert-eq nil (lookup-methods-by-name "Foo" :stage i :database path))
              (unless (or (oddp i) (< i 4))
                (assert-eq nil (lookup-methods-by-notation "x3x3x3x3x3x3x3x3x3x3x3x3,4"
                                                           :stage i :database path)))))
      (assert-eql 6 (length (lookup-methods-by-name "*" :stage 7 :database path)))
      (assert-eql 1 (length (lookup-methods-by-name "\\*" :stage 7 :database path)))
      (assert-eql 2 (length (lookup-methods-by-name "*\\**" :stage 7 :database path)))
      (assert-eql 2 (length (lookup-methods-by-name "?" :stage 7 :database path)))
      (assert-eql 1 (length (lookup-methods-by-name "\\?" :stage 7 :database path)))
      (assert-eql 2 (length (lookup-methods-by-name "*\\?*" :stage 7 :database path)))
      (assert-eql 2 (length (lookup-methods-by-name "\\\\*" :stage 7 :database path)))
      (assert-eql 2 (length (lookup-methods-by-name "?\\\\*" :stage 7 :database path)))
      (assert-eql 0 (length (lookup-methods-by-name "\\?\\\\" :stage 7 :database path)))
      (assert-eql 0 (length (lookup-methods-by-name "*\\\\*\\**" :stage 7 :database path)))
      (assert-eql 3 (length (lookup-methods-by-name "**********x***********" :stage 7 :database path)))
      (assert-eql 6 (length (lookup-methods-by-notation "1" :stage 7 :database path)))
      (assert-eql 1 (length (lookup-methods-by-notation "1" :stage 9 :database path)))
      (assert-eql 0 (length (lookup-methods-by-notation "1" :stage 11 :database path)))
      (assert-eql 6 (length (lookup-methods-from-changes '(!1325476) :database path)))
      (assert-eql 1 (length (lookup-methods-from-changes '(!132547698) :database path)))
      (assert-eql 0 (length (lookup-methods-from-changes '(!132547698E0) :database path))))))

#-(or clisp lispworks6 lispworks7)
(defun ringing-org-accessible-p ()
  (values (ignore-errors
            (multiple-value-bind (reply status)
                (drakma:http-request "http://www.ringing.org/"
                                     :method :head
                                     :connection-timeout 3)
              (declare (ignore reply))
              (eql status 200)))))

#-(or clisp lispworks6 lispworks7)
(define-constant +test-database-urls+
    '("http://www.ringing.org/static/test-roan-methods-1.zip"
      "http://www.ringing.org/static/test-roan-methods-2.zip")
  :test #'equal)

#-(or clisp lispworks6 lispworks7)
(define-test test-update-methods-database ()
  (let ((accessible (ringing-org-accessible-p)))
    (assert-true accessible)
    (when accessible
      (with-temp-filename (db1)
        (assert-true (update-methods-database :database db1 :url (first +test-database-urls+)))
        (let ((attributes (multiple-value-list (methods-database-attributes db1))))
          (assert-eql (parse-timestamp "2017-06-18 22:10:23") (second attributes))
          (assert-eql 22 (fourth attributes))
          (assert-equalp #(0 0 0 0 1 1 2 1 4 1 3 1 2 1 2 1 2 0 0 0 0 0 0 0 0)
                         (fifth attributes))
          (assert-false (update-methods-database :database db1 :url (first +test-database-urls+)))
          (assert-true (update-methods-database :database db1 :url (first +test-database-urls+) :force t))
          (assert-equalp attributes (multiple-value-list (methods-database-attributes db1)))
          (with-temp-filename (db2)
            (assert-true (update-methods-database :database db2 :url (second +test-database-urls+)))
            (every #'(lambda (x y) (not (equalp x y)))
                   (multiple-value-list (methods-database-attributes db2))
                   attributes))
          (let ((m1 (lookup-methods-by-name "Meall nan Eun Surprise" :stage 10 :database db1))
                (m2 (lookup-methods-by-name "Grandsire" :stage 8 :database db1)))
            (assert-eql 1 (length m1))
            (assert-eql 1 (length m2)))
          (let ((m2 (lookup-methods-by-name "Grandsire" :stage 8 :database db1
                                             :update :force :url (second +test-database-urls+)))
                (m1 (lookup-methods-by-name "Meall nan Eun Surprise" :stage 10 :database db1)))
            (assert-eql 1 (length m1))
            (assert-eql 0 (length m2)))
          (let ((m2 (lookup-methods-by-notation "3,1x1x1x1x" :stage 8 :database db1
                                                 :update :force :url (first +test-database-urls+)))
                (m1 (lookup-methods-by-name "Meall nan Eun Surprise" :stage 10 :database db1)))
            (assert-eql 1 (length m1))
            (assert-eql 1 (length m2)))
          (let ((m1 (lookup-methods-by-name "Meall nan Eun Surprise" :stage 10 :database db1))
                (m2 (lookup-methods-from-changes (parse-place-notation "3.1x1x1x1x1x1x1x8" :stage 8)
                                                  :database db1
                                                  :update :force :url (second +test-database-urls+))))
            (assert-eql 1 (length m1))
            (assert-eql 0 (length m2))))))))
