;;;; Copyright (c) 1975-2026 Donald F Morrison
;;;;
;;;; Permission is hereby granted, free of charge, to any person obtaining a copy of this
;;;; software and associated documentation files (the "Software"), to deal in the Software
;;;; without restriction, including without limitation the rights to use, copy, modify,
;;;; merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
;;;; permit persons to whom the Software is furnished to do so, subject to the following
;;;; conditions:
;;;;
;;;; The above copyright notice and this permission notice shall be included in all copies
;;;; or substantial portions of the Software.
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
;;;; INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
;;;; PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
;;;; HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
;;;; CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
;;;; OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

(in-package :roan/test)

(in-readtable :roan+interpol)

(define-test test-lru-cache ()
  (let* ((eql-cache-5 (make-lru-cache 5))
         (equalp-cache-4 (make-lru-cache 4 :test #'equalp))
         (eql-cache-1 (make-lru-cache 1))
         (caches (list eql-cache-5 equalp-cache-4 eql-cache-1))
         (x (list 1 2 3))
         (y (list 1 2 3)))
    (assert-true (every #'(lambda (c) (typep c 'lru-cache)) caches))
    (assert-true (every #'(lambda (c) (zerop (cache-count c))) caches))
    (assert-true (every #'(lambda (c) (multiple-value-bind (k f) (get-newest-key c)
                                        (and (null k) (not f))))
                        caches))
    (assert-true (every #'(lambda (c) (multiple-value-bind (v f) (get-newest-value c)
                                        (and (null v) (not f))))
                        caches))
    (assert-true (every #'(lambda (c) (multiple-value-bind (k f) (get-newest-key c x)
                                        (and (eq k x) (not f))))
                        caches))
    (assert-true (every #'(lambda (c) (multiple-value-bind (v f) (get-newest-key c x)
                                        (and (eq v x) (not f))))
                        caches))
    (dolist (c caches)
      (setf (getcache :x c) x)
      (assert-eq x (getcache :x c))
      (assert-eql 1 (cache-count c))
      (assert-equal '(:x t) (multiple-value-list (get-newest-key c)))
      (assert-equal (list x t) (multiple-value-list (get-newest-value c)))
      (assert-false (remcache :y c))
      (assert-true (remcache :x c))
      (assert-eql 0 (cache-count c))
      (assert-false (getcache :x c))
      (assert-equal '(nil nil) (multiple-value-list (get-newest-key c)))
      (assert-equal '(nil nil) (multiple-value-list (get-newest-value c)))
      (setf (getcache :x c) x (getcache :y c) y (getcache :n c) 1)
      (assert-eql 11 (incf (getcache :n c) 10))
      (assert-eql 11 (getcache :n c)))
    (assert-eql 1 (cache-count eql-cache-1))
    (assert-equal '(3 3 1) (mapcar #'cache-count caches))
    (assert-eq (getcache :x eql-cache-5) (getcache :x equalp-cache-4))
    (dolist (c caches)
      (setf (getcache x c) :x (getcache y c) :y))
    (assert-equal '(5 4 1) (mapcar #'cache-count caches))
    (assert-eq :x (getcache x eql-cache-5))
    (assert-eq :y (getcache y eql-cache-5))
    (assert-eq :y (getcache x equalp-cache-4))
    (assert-eq :y (getcache y equalp-cache-4))
    (assert-false (getcache x eql-cache-1))
    (assert-eq :y (getcache y eql-cache-1))
    (assert-true (remcache y eql-cache-1))
    (assert-eql 0 (cache-count eql-cache-1))
    (assert-eql 5 (cache-count eql-cache-5))
    (assert-true (remcache :n eql-cache-5))
    (assert-eql 4 (cache-count eql-cache-5))
    (dotimes (i 10)
      (setf (getcache i eql-cache-5) (expt i 2)))
    (dotimes (i 5)
      (assert-false (getcache i eql-cache-5))
      (assert-eql (expt (+ 5 i) 2) (getcache (+ 5 i) eql-cache-5)))
    (assert-true (remcache 6 eql-cache-5))
    (assert-true (remcache 7 eql-cache-5))
    (assert-false (remcache 4 eql-cache-5))
    (assert-eql 3 (cache-count eql-cache-5))
    (dolist (a '(:foo :bar :baz))
      (setf (getcache a eql-cache-5) (cons a a)))
    (assert-false (getcache 6 eql-cache-5))
    (assert-eq :nope (getcache 6 eql-cache-5 :nope))
    (dolist (c caches)
      (assert-eql 0 (cache-count (clrcache c)))
      (assert-eql 0 (cache-count c))))
  (dolist (tst (list 'eq #'eq))
    (let ((eq-cache (make-lru-cache 2 :test tst))
          (thing '(thing)))
      (setf (getcache :one eq-cache) 1)
      (setf (getcache thing eq-cache) 2)
      (setf (getcache :three eq-cache) 3)
      (assert-false (getcache :one eq-cache nil))
      (assert-eql 2 (getcache thing eq-cache 2))
      (assert-eql 3 (getcache :three eq-cache 3)))))

(define-test test-hash-sets ()
  (let* ((s1 (hash-set))
         (s2 (make-hash-set :size 10000 :rehash-size 10 :rehash-threshold 0.1))
         (s3 (hash-set-copy s1)))
    (assert-true (every #'hash-set-p (list s1 s2 s3)))
    (assert-false (some #'hash-set-p `(nil :foo 33 !132546 ,(make-hash-table))))
    (assert-equalp s1 s2)
    (assert-equalp s1 s3)
    (assert-equalp s2 s3)
    (assert-true (hash-set-subset-p s1 s2))
    (assert-true (hash-set-subset-p s2 s1))
    (assert-false (hash-set-proper-subset-p s1 s2))
    (assert-false (or (eq s1 s2) (eql s1 s2) (equal s1 s2)))
    (assert-false (or (eq s1 s3) (eql s1 s3) (equal s1 s3)))
    (assert-true (hash-set-empty-p s1))
    (assert-true (hash-set-empty-p s2))
    (assert-true (hash-set-empty-p s3))
    (assert-true (= (hash-set-count s1) (hash-set-count s2) (hash-set-count s3) 0))
    (assert-equal 10 (hash-set-count (hash-set nil 'foo :foo 0 1 (make-array 10)
                                              (hash-set nil 'foo :foo 0 1)
                                              !13572468 !0987654321 "13572468"
                                              (hash-set nil 'foo :foo 0 1)
                                              nil 'foo :foo 0 1)))
    (assert-false (hash-set-member nil s1))
    (assert-eq s1 (hash-set-nadjoin s1 !23564 !135246))
    (assert-true (hash-set-member !123564 s1))
    (assert-true (hash-set-member !135246 s1))
    (assert-false (hash-set-member !153246 s1))
    (assert-equalp s1 (hash-set !35246 !123564))
    (assert-equalp s1 (hash-set-adjoin s2 !35246 !123564))
    (assert-false (equalp s1 s2))
    (assert-false (hash-set-empty-p s1))
    (assert-equal 2 (hash-set-count s1))
    (assert-true (hash-set-empty-p s2))
    (assert-eq s1 (hash-set-clear s1))
    (assert-true (hash-set-empty-p s1))
    (assert-eq s1 (hash-set-clear s1))
    (assert-true (hash-set-empty-p s1))
    (assert-eq s1 (hash-set-nadjoin s1 !23564 !135246))
    (assert-eq s1 (hash-set-nadjoin s1 !35246))
    (assert-equalp s1 (hash-set !35246 !123564))
    (assert-equalp s1 (hash-set-adjoin s2 !35246 !123564 !135246))
    (assert-false (equalp s1 s2))
    (assert-false (equalp s1 s3))
    (assert-false (hash-set-empty-p s1))
    (assert-equal 2 (hash-set-count s1))
    (assert-equalp '("123564" "135246")
                   (sort (mapcar #'row-string (hash-set-elements s1)) #'string-lessp))
    (assert-eq s2 (hash-set-nadjoin s2 !35246 !123564 !135246))
    (assert-false (equalp s1 (hash-set-nadjoin s3 !35246)))
    (assert-equalp s1 (hash-set-nadjoin s3 !23564))
    (assert-equalp s1 s3)
    (assert-equalp (hash-set !23564) (hash-set-remove s1 !35246))
    (assert-equalp s1 s3)
    (assert-true (hash-set-empty-p (hash-set-delete s1 !23564 !35246)))
    (assert-true (hash-set-empty-p s1))
    (assert-eq s2 (hash-set-delete s2 !35246))
    (assert-equal 1 (hash-set-count s2))
    (multiple-value-bind (s n) (hash-set-remove s3 !35246)
      (assert-false (eq s3 s))
      (assert-equal 1 (hash-set-count s))
      (assert-equal 1 n)
      (assert-true (hash-set-member !35246 s3))
      (assert-false (hash-set-member !35246 s)))
    (multiple-value-bind (s n) (hash-set-remove s3 !53246)
      (assert-false (eq s3 s))
      (assert-equal 2 (hash-set-count s))
      (assert-true (null n)))
    (multiple-value-bind (s n) (hash-set-delete s3 !53246)
      (assert-true (eq s3 s))
      (assert-equal 2 (hash-set-count s))
      (assert-true (null n)))
    (multiple-value-bind (s n) (hash-set-delete s3 !35246)
      (assert-true (eq s3 s))
      (assert-equal 1 (hash-set-count s))
      (assert-equal 1 n)
      (assert-false (hash-set-member !35246 s3)))
    (assert-true (hash-set-subset-p s3 (hash-set !35246 !23564)))
    (assert-true (hash-set-proper-subset-p s3 (hash-set !35246 !23564)))
    (assert-true (hash-set-subset-p s3 (hash-set !23564)))
    (assert-false (hash-set-proper-subset-p s3 (hash-set !35246)))
    (assert-true (hash-set-subset-p s3 (hash-set !23564)))
    (assert-true (hash-set-subset-p s1 (hash-set !23564)))
    (setf s1 (hash-set 1 2 3 4 5 6 7 8 9 10))
    (assert-equalp (hash-set 1 2 7 8 9) (hash-set-difference s1 (hash-set 3 4 5 6 10)))
    (assert-equalp (hash-set 1 2 3 4 5 6 7 8 9 10) s1)
    (assert-eq s1 (hash-set-ndifference s1 (hash-set 1 3 5 7 9 11 12 13 0 nil :foo)))
    (assert-equalp (hash-set 2 4 6 8 10) s1)
    (assert-equalp s1 (hash-set-difference s1 (hash-set)))
    (assert-eq s1 (hash-set-ndifference s1 (hash-set)))
    (assert-equalp (hash-set 2 4 6 8 10) s1)
    (assert-equalp (hash-set 2 8 10) (hash-set-difference s1
                                                          (hash-set nil t nil 4 4 nil 4)
                                                          (hash-set)
                                                          (hash-set 4 5 6)))
    (assert-equalp (hash-set 2 4 6 8 10) s1)
    (assert-equalp (hash-set 2 8 10) (hash-set-ndifference s1
                                                           (hash-set nil t nil 4 4 nil 4)
                                                           (hash-set)
                                                           (hash-set 4 5 6)))
    (assert-equalp (hash-set 2 8 10) s1)
    (assert-equalp (hash-set 2 8 10) (hash-set-difference s1 (hash-set 1 3 5 7 9)))
    (flet ((test-extreme (sets test result &aux (len (length sets)))
             (setf sets (mapcar #'(lambda (s) (apply #'hash-set s)) sets)
                   result (elt sets result))
             (multiple-value-bind (extremum rest) (%extreme-hash-set (first sets) (rest sets) test)
               (assert-eq extremum result)
               (assert-equal (- len 1) (length rest))
               (assert-true (every #'(lambda (s) (member s sets)) rest)))))
      (test-extreme '(() (1 2) (1 2 3)) #'< 0)
      (test-extreme '((1 2 3) () (1 2) (1 2 3)) #'> 0)
      (test-extreme '((1 2) (1) (1 2 3)) #'< 1)
      (test-extreme '((1 2) (1 2 3) (1) () (1 3 2) ()) #'> 1)
      (test-extreme '((1) (1 2) (1 2 3) ()) #'< 3)
      (test-extreme '(() (1 2) (10 11) (1 2 3)) #'> 3))
    (multiple-value-bind (extremum rest) (%extreme-hash-set s1 (list s2 s3 s2 s1) #'<)
      (declare (ignore extremum))
      (assert-equal 2 (length rest)))
    (assert-equalp (hash-set 1 2) (hash-set-union (hash-set 1) (hash-set 2)))
    (assert-equalp (hash-set 1 2) (hash-set-union (hash-set 1 2) (hash-set) (hash-set)))
    (assert-equalp (hash-set 1 2 3)
                   (hash-set-union (hash-set) (hash-set 1 3) (hash-set 3 1) (hash-set 2 3)))
    (setf s1 (hash-set))
    (assert-equalp (hash-set 1 2 3) (hash-set-union s1 (hash-set) s1 s1 (hash-set 1 3) s1
                                                    (hash-set 3 1) (hash-set 2 3) s1))
    (assert-true (hash-set-empty-p s1))
    (setf s1 (hash-set 1 2 3 4 5 6 7 8 9 1 2 3 4))
    (setf s2 (hash-set))
    (assert-equalp (hash-set nil 1 2 3 4 5 6 7 8 9)
                   (hash-set-union s1 s2 (hash-set nil) s1 s2 s1))
    (assert-equalp (hash-set 1 2 3 4 5 6 7 8 9) s1)
    (assert-true (hash-set-empty-p s2))
    (assert-equalp (hash-set 1 2) (hash-set-nunion (hash-set 1) (hash-set 2) (hash-set)))
    (assert-eq s2 (hash-set-nunion s2 s1))
    (assert-equalp s1 s2)
    (assert-equalp (hash-set 1 2)
                   (hash-set-nunion (hash-set) (hash-set 2) (hash-set 1 2) (hash-set)))
    (assert-equalp (hash-set 1 2 3) (hash-set-nunion (hash-set 1 3) (hash-set 2 3)))
    (assert-equalp (hash-set 1 2 3)
                   (hash-set-nunion (hash-set 1 3) (hash-set 2 3) (hash-set 3 1)))
    (setf s1 (hash-set 1 2 3 4 5 6 7 8 9))
    (setf s2 (hash-set 2 4 6 8 10 12))
    (setf s3 (hash-set 4 8 16))
    (assert-equalp (hash-set 4 8) (hash-set-intersection s1 s2 s3))
    (assert-equalp (hash-set 1 2 3 4 5 6 7 8 9) s1)
    (assert-equalp (hash-set 2 4 6 8 10 12) s2)
    (assert-equalp (hash-set 4 8 16) s3)
    (assert-true (hash-set-empty-p (hash-set-intersection s1 (hash-set))))
    (assert-equalp (hash-set 4 8 16) (hash-set-intersection s3))
    (assert-true (hash-set-empty-p (hash-set-intersection (hash-set))))
    (assert-true (hash-set-empty-p (hash-set-intersection s1 s2 (hash-set nil t :foo) s3)))
    (assert-equalp (hash-set 4 8) (hash-set-nintersection s1 s2 s3))
    (assert-true (hash-set-empty-p (hash-set-nintersection (hash-set))))
    (assert-true (hash-set-empty-p (hash-set-nintersection (hash-set 1 2 3)
                                                           (hash-set nil t :foo))))
    (setf s1 (hash-set))
    (assert-eq nil (map-hash-set #'(lambda (x) (hash-set-nadjoin s1 (* 2 x)))
                                 (hash-set 1 11 3 5 7 9 5)))
    (assert-equalp (hash-set 2 6 10 14 18 22) s1)
    (assert-eq nil (map-hash-set #'(lambda (x) (when (> x 10) (hash-set-delete s1 x))) s1))
    (assert-equalp (hash-set 2 6 10) s1)
    (setf s1 (hash-set) s2 (hash-set nil))
    (assert-false (do-hash-set (e (hash-set 1 2 3 4 5))
                    (hash-set-nadjoin s1 (* e 2))
                    (hash-set-nadjoin s2 (* e 3))))
    (assert-equalp (hash-set 2 4 6 8 10) s1)
    (assert-equalp (hash-set nil 3 6 9 12 15) s2)
    (assert-equalp (hash-set nil 6 12)
                   (do-hash-set (e s2 s2)
                     (when (and e (oddp e)) (hash-set-delete s2 e))))
    (hash-set-clear s1)
    (assert-equalp (hash-set 2 4 6 8 10)
                   (do-hash-set (e (hash-set 1 2 3 4 5) (hash-set-union s1 s1 (hash-set)))
                     (hash-set-nadjoin s1 (* e 2))))
    (assert-equal '(3 6) (sort (iter (for e :in-hash-set s2) (when e (collect (/ e 2))))
                                #'<))
    (assert-eq nil (iter (for e :in-hash-set s2) (hash-set-delete s2 e)))
    (assert-true (hash-set-empty-p s2))
    (iter (with list := '(!132465 !87654321 17 :foo))
          (with set := (make-hash-set :initial-elements list))
          (for n :downfrom 4)
          (until (zerop n))
          (assert-eql n (hash-set-count set))
          (assert (member (hash-set-pop set) list :test #'equalp))
          (finally (assert (null (hash-set-pop set nil)))
                   (assert-equalp :empty (hash-set-pop set nil :empty))
                   (assert-error 'error (hash-set-pop set))))))

(defstruct test-hash-set-errors-test-struct roan::table)

(defparameter *test-hash-set-errors-fn* #'identity)

(define-test test-hash-set-errors ()
  (assert-error 'type-error (hash-set-copy '(1 2 3)))
  (assert-error 'type-error (hash-set-count #(1 2 3)))
  (assert-error 'type-error (hash-set-empty-p :foo))
  (assert-error 'type-error (hash-set-elements (make-hash-table :test #'equalp)))
  (assert-error 'type-error (hash-set-member 1 '(1)))
  (assert-error 'type-error (hash-set-subset-p (hash-set) nil))
  (assert-error 'type-error (hash-set-subset-p nil (hash-set)))
  (assert-error 'type-error (hash-set-proper-subset-p (hash-set) nil))
  (assert-error 'type-error (hash-set-proper-subset-p nil (hash-set)))
  (assert-error 'type-error (hash-set-clear (make-hash-table)))
  (assert-error 'type-error (hash-set-nadjoin :foo 1))
  (assert-error 'type-error (hash-set-adjoin nil 1))
  (let ((non-set (make-hash-table :test #'equalp)))
    (assert-error 'type-error (hash-set-nadjoin non-set :foo))
    (assert-error 'type-error (hash-set-delete non-set nil)))
  (assert-error 'type-error (hash-set-delete nil nil))
  (assert-error 'type-error (hash-set-remove t nil))
  (let ((non-set (make-test-hash-set-errors-test-struct
                  :table (make-hash-table :test #'equalp))))
    (assert-error 'type-error (hash-set-ndifference non-set (hash-set)))
    (assert-error 'type-error (hash-set-ndifference (hash-set 1) non-set))
    (assert-error 'type-error (hash-set-difference non-set (hash-set 1 2)))
    (assert-error 'type-error (hash-set-difference (hash-set nil) nil))
    (assert-error 'type-error (hash-set-union non-set non-set))
    (assert-error 'type-error (hash-set-union non-set (hash-set 1 2 3)))
    (assert-error 'type-error (hash-set-union (hash-set 'a 'b) non-set)))
  (assert-error 'type-error (hash-set-nunion (hash-set) :foo))
  (assert-error 'type-error (hash-set-nunion :foo))
  (assert-error 'type-error (hash-set-nunion :foo (hash-set)))
  (assert-error 'type-error (hash-set-intersection (hash-set) :foo))
  (assert-error 'type-error (hash-set-intersection :foo))
  (assert-error 'type-error (hash-set-intersection :foo (hash-set)))
  (assert-error 'type-error (hash-set-nintersection (hash-set) :foo))
  (assert-error 'type-error (hash-set-nintersection :foo))
  (assert-error 'type-error (hash-set-nintersection :foo (hash-set)))
  (assert-error 'type-error (map-hash-set #'identity '(1 2 3)))
  (assert-error 'type-error (do-hash-set (e '(1 2 3)) (declare (ignorable e))))
  (assert-error 'type-error (iter (for e :in-hash-set #(1 2 3)) (declare (ignorable e)))))

(define-test test-with-warnings-muffled ()
  (assert-warning 'style-warning (simple-style-warning "foo!"))
  (assert-warning 'warning (simple-style-warning "foo!"))
  (assert-no-warning 'style-warning
                     (with-warnings-muffled ()
                       (simple-style-warning "foo!")))
  (assert-no-warning 'warning
                     (with-warnings-muffled ()
                       (simple-style-warning "foo!")))
  (assert-no-warning 'style-warning
                     (with-warnings-muffled (:condition warning)
                       (simple-style-warning "foo!")))
  (assert-no-warning 'warning
                     (with-warnings-muffled (:condition warning)
                       (simple-style-warning "foo!")))
  (assert-no-warning 'warning
                     (with-warnings-muffled (:condition style-warning)
                       (simple-style-warning "foo!")))
  (assert-warning 'warning
                  (with-warnings-muffled (:condition style-warning)
                    (warn "foo!")))
  (let ((muffle t))
    (assert-no-warning 'warning
                       (with-warnings-muffled (:if muffle)
                         (simple-style-warning "foo!")))
    (assert-warning 'warning
                    (with-warnings-muffled (:if (not muffle))
                      (simple-style-warning "foo!")))
    (assert-no-warning 'warning
                       (with-warnings-muffled (:if muffle)
                         (setf muffle nil)
                         (simple-style-warning "foo!")))))

(define-test test-collapse-whitespace ()
  (let ((s1 "foo bar baz")
        (s2 " foo bar baz")
        (s3 "foo bar baz ")
        (s4 (format nil "foo~Cbar baz" #\Tab))
        (s5 "foo  bar baz")
        (s6 (format nil "~1{  ~C foo     ~C~C~C~C    bar baz ~}" '#0=(#\Tab . #0#)))
        (s7 "")
        (s8 " ")
        (s9 (format nil (format nil "~C" #\Tab))))
    (assert-eq s1 (collapse-whitespace s1))
    (iter (for s :in (list s2 s3 s4 s5 s6))
          (assert-equal s1 (collapse-whitespace s))
          (assert-false (eq s1 (collapse-whitespace s)))
          (assert-false (eq s (collapse-whitespace s))))
    (assert-eq s7 (collapse-whitespace s7))
    (iter (for s :in (list s8 s9))
          (assert-equal s7 (collapse-whitespace s))
          (assert-false (eq s7 (collapse-whitespace s)))
          (assert-false (eq s (collapse-whitespace s)))))
  (assert-eq nil (collapse-whitespace nil))
  (assert-error 'error (collapse-whitespace 5)))

(define-test test-same-type-p ()
  (assert-true (same-type-p 0 1))
  (assert-true (same-type-p :foo :bar))
  (assert-true (same-type-p (make-instance 'standard-object)
                            (make-instance 'standard-object)))
  (assert-false (same-type-p 0 t))
  (assert-false (same-type-p (make-instance 'standard-object) nil)))
