\input texinfo
@c %**start of header
@include inc/roan-version.texi
@settitle Roan @value{VERSION}
@setchapternewpage on
@footnotestyle end
@c %**end of header

@dircategory Software libraries
@direntry
* Roan: (roan).           Roan change ringing library
@end direntry

@copying
This is documentation of Roan, version @value{VERSION}.

This documentation is copyright @copyright{} 2015-2026 Donald F Morrison.

Copying and distribution of this documentation, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
@end copying

@titlepage
@title Roan
@subtitle Version @value{VERSION}
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@ifnottex
@c @validatemenus off
@node Top
@top
@insertcopying
@end ifnottex

@contents


@node Introduction
@chapter Introduction

@cindex change ringing
@cindex Common Lisp
@cindex introduction
@cindex Ringing Class Library
@cindex features
Roan is a library of
@url{https://en.wikipedia.org/wiki/Common_Lisp,Common Lisp}
code for writing applications related to
@url{https://www.ringing.org/change-ringing,change ringing}.
It is roughly comparable to the
@url{https://ringing-lib.sourceforge.net/,Ringing Class Library},
although that is for the C++ programming language, and the two libraries differ in many
other ways.

@cindex features
Roan provides
@itemize
@item
facilities for representing rows and changes as Lisp objects, and permuting them, etc.

@item
functions for reading and writing place notation, extended to support jump changes as well
as conveniently representing palindromic sequences of changes

@item
a set data structure suitable for collecting and proving sets of rows, or sets of sets of rows

@item
a pattern language for matching rows, for example, for identifying ones with properties
considered musically desirable; and that includes the ability to match pairs of rows,
which enables identifying wraps

@item
a data structure for describing methods, which can include jump changes,

@item
a searchable library of method definitions, together with a mechanism for
updating that library from the @url{https://cccbr.github.io/methods-library/,CCCBR Methods Library}

@item
a function for drawing blue lines of methods as Scalable Vector Graphics (SVG) images

@item
a function for extracting false course heads from common kinds of methods

@item
a representation of calls, allowing replacing, deleting or adding one or more changes to a
plain lead of a method, at any point within that lead, and possibly spanning two leads as
is done in doubles variations.
@end itemize

@cindex documentation
@cindex manual

While this manual describes Roan, it is neither a tutorial on Lisp nor one on change
ringing. If you don't know Common Lisp or don't know about change ringing, much of this
manual is likely to be confusing.

This manual is available online at @url{https://dfmorrison.github.io/} or as a PDF file at
@ifhtml
@html
<a href="https://dfmorrison.github.io/roan-manual.pdf" download>roan-manual.pdf</a>
@end html
@end ifhtml
@ifnothtml
@url{https://dfmorrison.github.io/roan-manual.pdf}
@end ifnothtml

@cindex license
Roan is distributed under an MIT open source license. While you should read it for
complete details, it largely means that you can just use Roan for nearly anything you like.
@xref{License}.
Roan also loads and uses a variety of other libraries. @xref{dependencies}.


@node Obtaining and installing Roan
@section Obtaining and installing Roan

@cindex Quicklisp
@cindex installation
@cindex downloading
@cindex ASDF
@cindex library
@cindex Bitbucket
While @url{https://www.quicklisp.org/beta, Quicklisp} is not required to run Roan, it is recommended.
With Quicklisp installed and configured, you can download and install Roan by simply
evaluating @code{(ql:quickload :roan)}.

Quicklisp's @code{quickload} function, above, will also pull in all the other libraries
upon which Roan depends; if you don't use Quicklisp you will have to ensure that those
libraries are available and loaded. If you don't want to use Quicklisp, and prefer to load
Roan by hand, the repository for Roan itself is at
@url{https://github.com/dfmorrison/roan}.

Note that Quicklisp creates a new distribution irregularly, these days it appears perhaps
once every six months or more, so there may be a lag
of that duration between when a new version is available in the GitHub repository and
when that version is available in Quicklisp. If you need it sooner, you may need to
download it yourself from GitHub.

@cindex Lisp implementations
Roan has been tested with at least
@itemize
@item
@url{https://sbcl.org, @acronym{SBCL, Steel Bank Common Lisp}} version 2.4.0 (ARM64) on
macOS 26.5
@item SBCL version 1.5.5 (x86-64) on Ubuntu Linux 18.04.3.
@item
and
@url{https://ccl.clozure.com, @acronym{CCL, Clozure CL}} version 1.11.5 (x86-64),
on Ubuntu Linux 18.04.3,
@end itemize
@noindent
but should also work in other, modern Common Lisp implementations that
support the libraries on which Roan depends. @xref{dependencies}.

@node Reporting bugs
@section Reporting bugs

The best way to report bugs is to submit them with
@url{https://github.com/dfmorrison/roan/issues, Roan's GitHub issue tracker}.
If that doesn't work for you you can also send mail
to Don Morrison <@email{dfmorrison@@gmail.com}>.

It would be helpful, and will be more likely to lead to successful resolution of the bug,
if a bug report includes
@itemize
@item
a detailed prescription of how to generate the bug, preferably from as simple a starting
place as you can use to reproduce it; that is, send code, that when evaluated,
demonstrates the bug

@item
the version of Roan you are using; this can be found by evaluating
@code{(asdf:component-version (asdf:find-system :roan))}

@item
if the problem might involve the lookup of methods, then also the output from
@code{(roan:method-library-details)}

@item
the name and version number of the Lisp implementation you are using, as well as whether
it is 32-bit or 64-bit if both are available

@item
the name and version number of the operating system on which it is running

@item
the kind of processor on which it is running, especially if it's something unusual
@end itemize


@node A note on examples
@section A note on examples

Examples in this manual are typically of the form
@example
(caddr '(1 2 3 4)) @result{}  3
@end example
@noindent
That is, an expression, followed by @samp{@result{}} and a printed
representation of the result of evaluating that expression. That right hand side is
typically not exactly as the @acronym{REPL, Read Eval Print Loop} might print it:
for example, symbols will usually be shown in lower case while most
Lisp implementation's @acronym{REPL}s will use upper case; and things like
hash-sets that have indeterminate order may result in different orders
of elements of lists.

Occasionally, though, examples will look like
@example
@group
CL-USER> (+ 1 2 3)
6
CL-USER> (values (+ 1 2 3) (cons 'a 'b))
6
(A . B)
CL-USER>
@end group
@end example
@noindent
In this case the example is a transcript of an interaction with a @acronym{REPL}@.
None of the examples makes explicit note of which of these two styles is being used,
it being assumed the reader can easily deduce this from their appearances.


@node The roan package
@section The roan package

@include inc/roan-summary.texi
@include inc/roan-package.texi
@include inc/use-roan-function.texi

@node Fundamental Types
@chapter Fundamental Types

@cindex change ringing
Central to change ringing is permuting sequences of a fixed collection of bells, where
the cardinality of that collection is the stage. For modeling such things Roan
provides the types @code{bell}, @code{stage} and @code{row}, and various operations
on them. It is also provides tools for reading and writing place notation.

@node Bells
@section Bells

@include inc/bell-summary.texi
@include inc/bell-type.texi
@include inc/bell-name-function.texi
@include inc/bell-from-name-function.texi
@include inc/print-bells-upper-case-variable.texi

@node Stages
@section Stages

@include inc/stage-summary.texi
@include inc/stage-type.texi
@include inc/minimum-stage-constant.texi
@include inc/maximum-stage-constant.texi
@include inc/stage-name-function.texi
@include inc/stage-from-name-function.texi
@include inc/default-stage-variable.texi


@node Rows
@section Rows

@include inc/row-summary.texi
@include inc/row-structure.texi
@include inc/roan-syntax-macro.texi

@anchor{row-p-function}
@cindex @code{row-p}
@deffn Function row-p object
Non-nil if and only if @var{object} is a @code{row}.
@end deffn

@include inc/stage-function.texi
@include inc/write-row-function.texi
@include inc/row-string-function.texi
@include inc/read-row-function.texi
@include inc/parse-row-function.texi
@include inc/row-function.texi
@include inc/rounds-function.texi
@include inc/bell-at-position-function.texi
@include inc/bells-list-function.texi
@include inc/reversed-row-function.texi

@node Properties of rows
@subsection Properties of rows

@include inc/roundsp-function.texi
@include inc/changep-function.texi
@include inc/placesp-function.texi
@include inc/in-course-p-function.texi
@include inc/involutionp-function.texi
@include inc/order-function.texi
@include inc/cycles-function.texi
@include inc/tenors-fixed-p-function.texi
@include inc/which-plain-bob-lead-head-function.texi
@include inc/which-grandsire-lead-head-function.texi

@node Permuting rows
@subsection Permuting rows

@include inc/permute-function.texi
@include inc/permute-collection-generic-function.texi
@include inc/generate-rows-generic-function.texi
@include inc/permutation-closure-function.texi
@include inc/inverse-function.texi
@include inc/permute-by-inverse-function.texi
@include inc/alter-stage-function.texi


@node Place notation
@section Place notation

Place notation is a succinct notation for writing sequences of changes, and is widely used
in change ringing. Roan provides functions for reading and writing place notation,
producing lists of @code{row}s, representing changes.

@include inc/parse-place-notation-summary.texi

@include inc/parse-place-notation-function.texi
@include inc/read-place-notation-function.texi
@cindex writing place notation
@cindex formatting place notation
@cindex comma
@cindex @samp{,} in place notation
@cindex jump changes
@include inc/write-place-notation-function.texi
@include inc/place-notation-string-function.texi
@include inc/canonicalize-place-notation-function.texi
@include inc/cross-character-variable.texi


@node Hash-sets
@chapter Hash-sets

@include inc/hash-set-summary.texi
@include inc/hash-set-structure.texi
@include inc/make-hash-set-function.texi
@include inc/hash-set-function.texi
@include inc/hash-set-copy-function.texi

@node Properties of hash-sets
@section Properties of hash-sets

@include inc/hash-set-count-function.texi
@include inc/hash-set-empty-p-function.texi
@include inc/hash-set-elements-function.texi
@include inc/hash-set-member-function.texi
@include inc/hash-set-subset-p-function.texi

@node Modifying hash-sets
@section Modifying hash-sets

@include inc/hash-set-clear-function.texi
@include inc/hash-set-adjoin-function.texi
@include inc/hash-set-remove-function.texi
@include inc/hash-set-delete-function.texi
@include inc/hash-set-pop-function.texi
@include inc/hash-set-difference-function.texi
@include inc/hash-set-union-function.texi
@include inc/hash-set-intersection-function.texi

@node Iterating over @code{hash-set}s
@section Iterating over @code{hash-set}s

@include inc/map-hash-set-function.texi
@include inc/do-hash-set-macro.texi

@cindex @code{iterate}
In addition, it is possible to iterate over a @code{hash-set} using
the @url{https://common-lisp.net/project/iterate/,@code{iterate}} macro,
by using the @code{for...:in-hash-set...} construct.
@example
@group
(iter (for element :in-hash-set (hash-set !135246 !123456 !531246))
      (collect (list element (in-course-p element))))
    @result{} ((!531246 nil) (!135246 nil) (!123456 t))
@end group
@end example


@node Patterns
@chapter Patterns

@include inc/row-match-p-summary.texi
@include inc/row-match-p-function.texi
@include inc/parse-pattern-function.texi
@include inc/format-pattern-function.texi
@include inc/named-row-pattern-generic-function.texi
@include inc/pattern-parse-error-class.texi

@node Counting matches
@section Counting matches

@include inc/match-counter-summary.texi
@include inc/match-counter-structure.texi
@include inc/make-match-counter-function.texi
@include inc/add-pattern-function.texi
@include inc/remove-pattern-function.texi
@include inc/remove-all-patterns-function.texi
@include inc/match-counter-pattern-function.texi
@include inc/match-counter-labels-function.texi
@include inc/match-counter-counts-function.texi
@include inc/reset-match-counter-function.texi
@include inc/match-counter-handstroke-p-function.texi
@include inc/record-matches-function.texi


@node Methods
@chapter Methods

@include inc/method-summary.texi
@include inc/method-class.texi
@include inc/method-function.texi

@anchor{method-stage-function}
@anchor{method-name-function}
@anchor{method-place-notation-function}
@deffn Function method-name method
@deffnx Function method-jump-p method
@deffnx Function method-differential-p method
@deffnx Function method-little-p method
@deffnx Function method-class method
@deffnx Function method-stage method
@deffnx Function method-place-notation method
Return the name, classification details, stage and place notation of @var{method}, or
@code{nil}. A non-nil value returned by @code{method-name} or @code{method-place-notation}
is a string; by @code{method-stage} a @code{stage} (that is, an integer); and by
@code{method-class} one of the keywords @code{:bob}, @code{:place}, @code{:surprise},
@code{:delight}, @code{:treble-bob}, @code{:alliance}, @code{:treble-place},@code{:hybrid},
or @code{:hunt}. The predicates @code{method-jump-p}, @code{method-differential-p} and
@code{method-little-p} return generalized booleans.
These functions all signal a @code{type-error} if @var{method} is not a @code{method}.

Note that @code{method-jump-p} reflects the classification stored in @var{method}, while
@code{method-contains-jump-changes-p} reflects the place notation of @var{method}, and
they may not agree.

All these functions may be used with @code{setf} to set the relevant attributes of
@var{method}. No checking is done that the string supplied as the
@code{method-place-notation} is, in fact, valid place notation; however, a subsequent
attempt to use invalid place notation, for example by @code{method-changes} or
@code{method-lead-head}, will signal an error. Attempting to set the name or place
notation to anything but a string or @code{nil}, the class to anything but @code{nil} or
one of the appropriate keywords, or the stage to anything but a @code{stage} or @code{nil}
signals a @code{type-error}.
@xref{method-contains-jump-changes-p}
@end deffn

@include inc/copy-method-function.texi

@include inc/method-title-function.texi
@include inc/method-from-title-function.texi
@include inc/comparable-method-name-function.texi
@include inc/inconsistent-method-specification-error-class.texi

@cindex Central Council
@cindex CCCBR
@cindex FMR
@cindex Framework
@cindex methods
@cindex place notation
@cindex library
@cindex lookup
@cindex query
@cindex library
@node Methods library
@section Methods library

@include inc/lookup-methods-summary.texi
@include inc/lookup-methods-function.texi
@include inc/lookup-method-info-function.texi
@include inc/update-method-library-function.texi
@include inc/method-library-details-function.texi
@include inc/method-library-error-class.texi

@section Functions of the place notation of methods

@include inc/canonicalize-method-place-notation-function.texi
@include inc/method-changes-function.texi
@include inc/method-contains-jump-changes-p-function.texi
@include inc/method-lead-head-function.texi
@include inc/method-lead-count-function.texi
@include inc/method-plain-lead-function.texi
@include inc/method-lead-length-function.texi
@include inc/method-course-length-function.texi
@include inc/method-plain-course-function.texi
@include inc/method-true-plain-course-p-function.texi
@cindex classification
@cindex Central Council
@cindex CCCBR
@cindex methods
@include inc/method-hunt-bells-function.texi
@include inc/method-working-bells-function.texi
@include inc/method-lead-head-code-function.texi
@cindex symmetry
@cindex palindromes
@include inc/method-conventionally-symmetric-p-function.texi
@cindex rotations
@include inc/method-rotations-p-function.texi
@include inc/method-canonical-rotation-key-function.texi

@cindex classification
@cindex Central Council
@cindex CCCBR
@cindex FMR
@cindex Framework
@include inc/classify-method-function.texi
@include inc/no-place-notation-error-class.texi

@cindex blueline
@cindex blue line
@cindex line
@cindex SVG
@cindex graphic
@section Drawing blue lines
@include inc/blueline-function.texi

@cindex falseness
@cindex false course head groups
@cindex summary falseness
@cindex incidence of falseness
@cindex Hodgson, Maurice
@cindex Baldwin, Roger
@cindex Shuttleworth, Edmund
@cindex Leary, John
@node Falseness
@chapter Internal Falseness

@include inc/fch-group-summary.texi
@include inc/fch-group-structure.texi
@include inc/fch-group-function.texi

@anchor{fch-group-name-function}
@anchor{fch-group-parity-function}
@anchor{fch-group-elements-function}
@deffn Function fch-group-name group
@deffnx Function fch-group-parity group
@deffnx Function fch-group-elements group
Returns the name, parity or elements of the @code{fch-group} @var{group}.

The value returned by @code{fch-group-name} is a string of length one or two. For major
groups it is always of length one, and is a letter. For higher stages if of length one it
is again a letter, and if of length two it is a letter followed by the digit @samp{1} or
the digit @samp{2}. The case of letters in @code{fch-group} names is significant.

For major @code{fch-group}s @code{fch-group-parity} always returns @code{nil}. For higher
stage @code{fch-group}s it always returns either @code{:in-course} or
@code{:out-of-course}.

The @code{fch-group-elements} function returns a list of @code{row}s, the elements of the
group. For major groups these are always major @code{row}s, and for higher stage groups
royal @code{rows}. The @code{alter-stage} fucntion (@pxref{alter-stage}) can be helpful
for making such @code{row}s conform to the needs of other stages above major.

All three functions signal a @code{type-error} if @var{group} is not a @code{fch-group}.
@end deffn

@include inc/fch-groups-string-function.texi
@include inc/method-falseness-function.texi



@cindex calls
@cindex immutable
@cindex bob
@cindex single
@cindex variations, doubles
@cindex doubles variations
@node Calls
@chapter Calls
@c
@include inc/call-summary.texi
@include inc/call-structure.texi
@include inc/call-function.texi
@include inc/call-apply-function.texi
@include inc/call-application-error-class.texi


@node License
@appendix License

@cindex license

Roan is covered by an
@url{https://en.wikipedia.org/wiki/MIT_License,MIT open source license},
a well-known, permissive license with few compatibility
problems with other licenses. The license is quoted below. Loading Roan also
loads several third party libraries, each of which is made available under its own
terms, distinct from Roan's. To the best of my understanding all the libraries Roan
loads are either in the public domain, or have suitably permissive licenses; however, you should
read their actual licenses to be sure. @xref{dependencies}.

Roan's license is:
@quotation
Copyright (c) 1975-2026 Donald F Morrison

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify,
merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be included in all copies
or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
@end quotation


@node Libraries Used by Roan
@appendix Libraries Used by Roan

@anchor{dependencies}
@cindex library
@cindex license
@cindex dependencies

Roan loads the following libraries.
Note that it does not include them as part of itself, it merely loads them, typically
over the network from Quicklisp's library server.

While most are in the public domain or
offered under a permissive, open source license, some are offered with a
@url{https://en.wikipedia.org/wiki/Copyleft,,copyleft} license.
This should make no difference for using Roan in the usual way, with
the libraries loaded from Quicklisp. But if you distribute something built with Roan
and include the libraries in it you will have to pay attention to these licenses and be
sure to adhere to them.

@itemize
@item
@url{https://common-lisp.net/project/alexandria/draft/alexandria.html,Alexandria} [public domain]
@item
@url{https://common-lisp.net/project/iterate,Iterate} [MIT]
@item
@url{https://edicl.github.io/cl-interpol/,CL-INTERPOL} [BSD]
@item
@url{https://common-lisp.net/project/asdf/,ASDF} [MIT]
@item
@url{https://weitz.de/cl-fad/,CL-FAD} [BSD]
@item
@url{https://common-lisp.net/project/local-time/,local-time} [MIT]
@item
@url{https://github.com/dardoria/uuid/blob/master/uuid.lisp,uuid} [LLGPL]
@item
@url{https://weitz.de/cl-ppcre,CL-PPCRE} [BSD]
@item
@url{https://weitz.de/drakma/,Drakma} [BSD]
@item
@url{https://shinmera.com/docs/plump/, Plump} [Artistic]
@item
@url{https://github.com/froydnj/binascii,binascii} [BSD]
@item
@url{https://common-lisp.net/project/zip/,ZIP} [BSD+LGPL]
@end itemize

Note that several of these libraries in turn load others, if embedding them in something
you ship you may need to pay attention to the licenses of things transitively included.

Several further libraries are used in the construction of Roan, but their license terms should
not affect those who use or ship Roan itself, except possibly in so far as they need to use
them to develop modifications to Roan.

While not loaded during normal use of Roan, when running Roan's unit tests (@pxref{testing})
the following library is also loaded and used.

@itemize
@item
@url{https://github.com/AccelerationNet/lisp-unit2,lisp-unit2} [MIT]
@end itemize

Also while not loaded during normal use of Roan, when building Roan's documentation
(@pxref{building}) the following libraries are also loaded and used. One of these, too,
@code{trivial-documentation}, is offered under a copyleft license.
To the best of my understanding this should not affect those simply copying or
distributing Roan, so long as they do not include a copy of @code{trivial-documentation}
with it.

@itemize
@item
@url{https://weitz.de/cl-fad/,CL-FAD} [BSD]
@item
@url{https://github.com/eugeneia/trivial-documentation,trivial-documentation} [Affero GPL]
@end itemize


@cindex UNIX
@cindex Apollo
@cindex Domain Lisp
@cindex Lisp Machine
@cindex Macintosh Common Lisp
@cindex CLISP
@cindex @acronym{C}
@cindex bluelines
@cindex calls
@cindex drawing
@node History
@appendix History

Roan started out in the mid-1970s as code to support searching for compositions using
Portable Standard Lisp on a Digital Equipment Corporation DEC-10 machine. A few years
later a bunch of utilities for UNIX, written in @acronym{C}, were added. By the mid-1980s
it had expanded significantly into collections of Apollo Domain Lisp and Lisp Machine Lisp
code. From there to a highly portability-challenged version for Digitool Macintosh Common
Lisp, followed by a more portable version that I used for several years, predominately
with CLISP. Over the years I've even ``ported'' it (if you can call a complete rewrite in
a different language a ``port'') to a few other programming languages where I used it for
various lengths of time. Eventually I tried to make a more tidy, fairly portable Common
Lisp version, and have been happily using this for my compositional activities in recent
years. It also underpins the method presentation stuff on the
@url{https://www.ringing.org/,ringing.org} website.

Over the years several folks received copies of it, and in some cases used it, at least
for a little while. I think it was used for a time on a Lisp Machine to drive a set of
electronic Christmas tree ornamental bells ringing touches! But despite such use, it was
never well organized or documented.

In a fit of good-neighorliness I've finally tried to make it sufficiently tidy for more
general distribution and added this documentation, in the hopes that others may find it
useful, too.

@anchor{future-plans}
As you can easily deduce from its history, lots of things have come and gone over the
years, and there are lots of parts that have fallen into disrepair or don't play well with
other parts. In tidying it up for distribution I'm trying to fix that. Public releases of
Roan will contain only portions that have been reasonably well tested and that do play
well together, but there's still a lot of work to do resurrecting, tidying and documenting
other features of varied antiquity and robustness. I'm hopeful that in coming months and
years I'll be able to offer more releases with more good stuff added to them.


@node What's with the name?
@section What's with the name?

@cindex Robert Roan
@cindex Fabian Stedman
@cindex Stedman, Fabian
@cindex Plain Bob Minor
@cindex Grandsire Doubles
@cindex standard extent

Robert Roan was an important seventeenth century ringer and composer. He is widely
believed to have invented Grandsire Doubles and Plain Bob Minor, and by implication, the
``standard extent'' of minor.

Sadly, his name is less well known among most ringers than some other early composers,
probably because he's had the misfortune of never having had a method named after him.
So several decades ago it seemed fitting to name a library of software intended
for use in composition after him. In keeping with Robert Roan's relative obscurity, it's
taken several decades for the eponymous software to become publicly available.


@cindex Quicklisp
@cindex ASDF
@node Building and Modifying Roan
@appendix Building and Modifying Roan

Since Roan is written in Lisp there really is no build process: your Lisp implementation,
under the direction of Quicklisp and ASDF, will happily just compile and load it.

However, the documentation does have a slightly complex build process. And if you
are modifying Roan you really should make friends with the unit tests.

@cindex building
@cindex documentation
@cindex manual
@node Building the documentation
@section Building the documentation

@anchor{building}

@cindex Texinfo
@cindex @code{extract-documentation}
@cindex @file{Makefile}
@cindex @acronym{PDF}
@cindex @acronym{HTML}
@cindex Info
This manual is written using
@url{https://www.gnu.org/software/texinfo/, GNU Texinfo}.
Depending upon how your environment is already configured you may have to download
and install Texinfo software, TeX and/or LaTeX.

There is a file included in the source tree, though not a part of Roan per
se, @file{extract-documentation.lisp}, that is used to extract the documentation
strings associated with symbols exported from the @code{roan} package. This
is done using the @code{roan/doc:extract-documentation} function. For each exported
symbol it writes a small @file{.texi} file in the @file{doc/inc} directory
with its documentation
string, augmented with some further Texinfo commands. The documentation strings in
the Roan sources are themselves infested with appropriate Texinfo commands.
Most of these small files are then @code{@@include}d into the main Texinfo file,
@file{roan.texi}, to document the various functions, macros and types.
In addition to @file{roan.texi}, there is also a small collection of style
information used by the @acronym{HTML} versions of the documentation in
@file{roan.css}.

After the documentation strings have been extracted @command{makeinfo} needs to
be called for each of the four versions of the documentation that are produced:
@itemize
@item
an Info file
@item
a @acronym{PDF} file
@item
a single @acronym{HTML} file
@item
a collection of @acronym{HTML} files, one per chapter
@end itemize

@cindex Steel Bank Common Lisp
@cindex SBCL
So long as SBCL (Steel Bank Common Lisp) is installed, the @file{Makefile} in the source
hierarchy should do all this for you.
If preferred, the @file{Makefile} can be easily modified to use a different Lisp
implementation to run @code{extract-documentation}.
Note that if you are using SBCL it will emit several warnings about an inability to
find docstrings for an SBCL internal type; these warnings can be safely ignored.

@cindex Edward Smith
@cindex Smith, Edward
@cindex @emph{Titanic}
@cindex @acronym{RMS} @emph{Titanic}
If a public function is added to Roan, it should include a suitable documentation string,
and @file{roan.texi} should be revised to give it an appropriate home, where the
corresponding @file{inc/*-function.texi} file is @code{@@include}d. So long as you export
its name from the @code{roan} package it should be picked up when building the
documentation.
Then, run
@command{make documentation} and if all goes
well@footnote{According to John Pladdys
``If all goes well'' was a favorite expression of the sea captain Edward Smith.},
all four kinds of documentation will be nicely produced a few seconds later.

Of course, most of the time, all won't go well. Besides looking carefully at the rather noisy
output from @command{makeinfo}, here are a few other things to bear in mind:
@itemize
@item
Even though a problem looks like it's in @file{roan.texi}, it might be in a
documentation string in a source file; Texinfo is pretty good about
identifying the include file that's causing the problem, unless the problem
is just too subtle for it.

@item
@cindex @samp{@@}-sign
@cindex at-sign
@cindex braces
Any occurrences of braces, @samp{@{@}}, or an at-sign, @samp{@@}, in a documentation string
will be interpreted magically by Texinfo, and need to be quoted with an @samp{@@}.

@item
@cindex @samp{"}
@cindex quotes
When writing examples in documentation strings, if the examples use Lisp strings, the double
quotes need to be escaped with back slashes, or Lisp will become confused.

@item
@cindex parentheses
@cindex Emacs
@cindex fill-paragraph
Even if you are not one yourself, be nice to Emacs users. In Lisp mode Emacs treats an
open parenthesis, @samp{(}, at the beginning of a line specially, and will become badly
confused if you have such in a documentation string. When writing examples, indent such
Lisp code by one space to keep Emacs happy. Similarly be sure to format documentation
strings so that parenthetical comments do not start at the beginning of a line; Emacs's
own @code{fill-paragraph} command is careful about that on your behalf.

@item
Texinfo is a complex system. If you're going to use it, you're going to have to learn a
bit about it. Until you become facile with it its usually easiest to make changes slowly
and incrementally.

@item
Writing good documentation is often harder than writing the corresponding code.
@end itemize


@cindex tests
@cindex unit tests
@cindex lisp-unit2
@node Running unit tests
@section Running unit tests

@anchor{testing}

The Roan source tree contains a collection of unit tests. If you are making changes to Roan
it is @emph{highly} recommended that you make friends with them and use them early and
often. Unless run on an unusally slow machine or Lisp implementation it takes less than
a minute to run the full collection, and in the long run they will save you a lot of time.

The unit tests live in their own package, @code{roan/test}, and make use of a further library
not included in Roan itself, @url{https://github.com/AccelerationNet/lisp-unit2,lisp-unit2}.
After running  @code{(ql:quickload :roan/test)} it should be possible to run all the
unit tests by simply evaluating @code{(roan/test:test-roan)}. If the unit tests all succeed
it will report the success of about 13,000 assertions with no failures. Otherwise, you'll
have some debugging to do.

One caveat: a few of the tests, related to upgrading the methods library, require access
to the internet. If it is not available, there will be a failures reported.

If you make changes to Roan I suggest you run the unit tests frequently. If you care about
portability, run them at least occasionally on as many different Lisp implementations as
you have access to. And if you add functions to Roan, add unit tests for them, too.

Writing decent, reusable tests is often harder and more time consuming than writing code;
but it's a lot easier and less time consuming than debugging things days, weeks, months or
years after they were first written. This is especially true for a relatively low-level
library such as Roan.



@c Can't call the index just "Index" 'cause that produces two, different index.html's! Sigh.
@node Documentation Index
@unnumbered Index

@printindex cp



@bye
